### ISSUE TITLE
Thai BN.1.3.2 singlet with 3 S deletions and a few unusual S mutations

### ISSUE THREAD

**Issue by corneliusroemer** [sars-cov-2-variants/lineage-proposals#1041]
hCoV-19/Thailand/NIC_NPM_POS4557/2023|EPI_ISL_18449892|2023-10-13

<img width="575" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/fca03afc-4b89-4e94-ad25-7c3fdda89f50">

<img width="1524" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/e2893623-53a8-4459-b524-2273d085157e">

<img width="1011" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/67d24709-b3bf-4e94-9233-8419283bfb34">

https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_21079_141670.json

Does Usher throw these out at the moment? Maybe we should have an "interesting singlets" list similar to "recombinants.tsv" to force include them when they appear real?

**Comment by ryhisner** [comment]
Yeah, this is one of two from Thailand today that lost both ends of the C15-C136 disulfide bond, which causes major conformational changes in the NTD. This one has ∆14-16, and ∆136-139, and the other one (EPI_ISL_18449647, collected in June) has P9L (which causes the loss of C15 due to a change in signal peptide length) and ∆135-139. 

But neither of those is the most interesting one from Thailand today. That honor goes to this BA.2 with 22 spike mutations, including the extremely rare R498Q reversion. This is one of two relatively recent sequences I've seen with R498Q, and both added multiple ACE2-affinity-increasing mutations to make up for the huge loss of the ACE2 affinity from R498Q. 

This one has Y453F, FLip (L455F-F456L), N460K, and R493Q. Below are the private mutations as I see them.

<img width="1475" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/64337880-4374-40ad-88db-3dbef1ba2b52">

Usher unfortunately puts it on an entirely artifactual branch that lumps together a ton of divergent BA.2 sequences because they share N460K and R493Q.

**Comment by FedeGueli** [comment]
no new sample came out of this . closing it for now
