### ISSUE TITLE
> > > > I konw about BA.2.86.* growing so fast,but I do not konw why is BA.2.86. * not growing in China?

### ISSUE THREAD

**Issue by Memorablea** [sars-cov-2-variants/lineage-proposals#1043]
> > > > I konw about BA.2.86.* growing so fast,but I do not konw why is BA.2.86. * not growing in China?
> > > 
> > > 
> > > BA.2.86 is not growing that fast. HK.3 is faster spreading and was already well established by the time vanilla BA.2.86 was introduced.  JN.1 may be growing fast but is too recent and distant to have spread there yet.
> > 
> > From what do you conclude that HK.3 is faster then BA.2.86?
> > 
> > Here is a CovSpectrum query, with purple being HK.3, orange BA.2.86* without JN.1, green JN.1. Please click on regions to get a better impression.
> > 
> > In the US HK.3 seems faster than BA.2.86 without JN.1, with JN.1 growing fast. But in many other countries BA.2.86* seems to compete well with HK.3.
> 
> I think what he said is about the situation within China.

With only 2 BA.2.86 in China so far, we can't say anything about its growth there yet and I don't think he meant that. But maybe he @jasondorjeshort will tell us himself what he meant.

_Originally posted by @JosetteSchoenma in https://github.com/sars-cov-2-variants/lineage-proposals/issues/606#issuecomment-1787387349_

**Comment by Memorablea** [comment]
误操作

**Comment by jasondorjeshort** [comment]
What I meant was that since HK.3 and BA.2.86.1 are of similar rates of spread, because HK.3 was fully established in China before BA.2.86.1 started showing up you wouldn't expect a significant relative growth rate out of BA.2.86.1 at all.  This is very similar to the situation with Alpha and Gamma or BA.5 and BA.2.75.  Each of those times a slightly faster variant came along, but because it was later enough that the almost-as-fast one it never made "noticeable" inroads into countries where the earlier one was already highly prevalent.

China being the origin point of HK.3 and BA.2.86/BA.2.86.1/JN.1's origin points being on the opposite side of the world are the cause there.  China's numbers are very limited, but assuming HK.3 has already peaked high and is on a relatively swift decline. BA.2.86.1 is likely to also be on an absolute decline.  This is actually comparable to the situation in the US, where our FL.1.5.1 peak has made BA.2.86.1 essentially flat.  But if HK.3 has peaked then population immunity will overall be much higher.

@JosetteSchoenma sorry to highlight you again. I did misread your query, sorry about that.  But it overall doesn't change the point that HK.3 is roughly a contemporary of BA.2.86 and BA.2.86.1 and it will take forever for either to catch up if the other has even a 1000x relative starting advantage.  

Every new XBB  infection should give BA.2.86* a slight relative growth advantage, while also depressing its growth absolutely - because population immunity to BA.2.86 rises after these infections, but immunity to XBB rises more.  Since HK.3 has not peaked in the US this implies the BA.2.86 variants will gain an advantage by the time it subsides (which may be the case in Europe already, that I'm not sure of).  But it also means the BA.2.86 family should have a larger relative advantage in China, while most of them probably should not be growing absolutely.

**Comment by Memorablea** [comment]
THX YOU
