### ISSUE TITLE
JN.1.1 plus S:R346S ( 5 seqs France, 1 with S:F486P>R) 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1148]
Defining mutations:
JN.1.1 > C11747T > C21952T  > S:R346S (A22600C) 

Query: C11747T ,C21952T ,A22600C

Samples: 2 France
EPI_ISL_18569011, EPI_ISL_18577423

Tree:
![Schermata 2023-12-04 alle 13 04 12](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b4df9ea0-0f79-4f2e-bba9-b423118b4067)
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_51659_dbeba0.json?c=userOrOld&label=id:node_11164096

Notes:
One of the two sequences has C23019G in S:486  resulting S:F>P486R

cc @corneliusroemer @ryhisner @angiehinrichs @thomasppeacock flagging this mutation .

(Nextclade doesnt read it correctly, scratch it i was looking at the to other sequence without 486R sorry)

**Comment by jbloom** [comment]
I actually worry that R346S is likely to be a fairly significant antibody escape mutation in BA.2.86-like backgrounds (such as JN.1.1). The reason is that it is adding to BA.2.86-like strains (such as JN.1*) an important antibody-escape mutation that XBB-like viruses already have, but BA.2.86-like viruses lack.

Specifically, when you look at @Bernadetadad's [XBB.1.5 serum escape data](https://dms-vep.github.io/SARS-CoV-2_XBB.1.5_spike_DMS/htmls/summary_overlaid.html) or the [antibody-escape calculator relative to XBB](https://jbloomlab.github.io/SARS2-RBD-escape-calc/) with Yunlong Cao's antibody escape data, site 346 does not look like a particularly significant escape site. But this is because XBB already has a mutation at site 346 relative to Wuhan-Hu-1 (R364T)!

Recall that BA.2.86 lacks the escape mutation at site 346, and instead still has the ancestral Wuhan-Hu-1 like R346 identity (see [here](https://slides.com/jbloom/new_2nd_gen_ba2_variant#/15)). If you look at [Bernadeta's data](https://dms-vep.github.io/SARS-CoV-2_XBB.1.5_spike_DMS/htmls/summary_overlaid.html) and click the option at the bottom **not** to floor escape at zero, you can then see that reverting T346R at site 346 is a significant sensitizing mutation (leads to better neutralization). Likewise, if you look at the RBD escape calculator Yunlong Cao's data but change the `virus against with neutralization measured` to BA.2 (which lacks R346T) you see that site 346 is a major escape mutation.

All that to say, most people probably still have substantial serum neutralization activity targeting R346 from earlier strains, and so this site could substantially contribution to neutralization of BA.2.86 / JN.1. Therefore, the R346S mutation could be a meaningful antibody escape mutation in that background.

I don't know what to make of the P486R. Neither our (Bernadeta's) serum escape nor ACE2 binding data suggest this mutation is beneficial in XBB-like backgrounds, nor do @tylernstarr's [yeast-display DMS data](https://tstarrlab.github.io/SARS-CoV-2-RBD_DMS_Omicron-XBB-BQ/RBD-heatmaps/). Either P486R is not beneficial, or there has been some epistasis due to other mutations in BA.2.86 that change its effect on ACE2 binding relative to what is measured in BA.2 or XBB.1.5.

**Comment by FedeGueli** [comment]
Thank you very.much @jbloom !

**Comment by tylernstarr** [comment]
Interesting, and agree with Jesse's summary. Possible that the 483 deletion could modulate impact of mutations at 486. We have yeast RBD DMS data in the [SARS-Cov-1 Urbani background](https://tstarrlab.github.io/SARSr-CoV-RBD_DMS/RBD-heatmaps_delta/), which likewise has a deletion at ~483 relative to SARS2 (depends on exact alignment where the deletion is placed). In our SARS1 data, R at 486 looks less deleterious for ACE2 affinity than it does in some of the SARS2 backgrounds -- a little bit worse binding than L486 or F486, but better than e.g. P486.

Obviously a lot more sequence differences in SARS-CoV-1 so many potential causes at play. We should have yeast RBD DMS data in BA.2.86 sometime in Jan/Feb if all goes well.

**Comment by thiolist** [comment]
The R364S mutation removes a cleavage site which could otherwise be cleaved by the soluble trypsin-like protease HAT (Human Airway Trypsin-like protease) which is present in the mucus lining the human airway tissues. When cleaved (R364), the protein "tails" on each side are free to adopt whatever conformation they want.

But for 364S, these two ends are no longer free to diverge from each other, which could drastically change the local conformation of the protein, leading to antibody evasion.

See: https://github.com/cov-lineages/pango-designation/issues/2180

**Comment by FedeGueli** [comment]
> The R364S mutation removes a cleavage site which could otherwise be cleaved by the soluble trypsin-like protease HAT (Human Airway Trypsin-like protease) which is present in the mucus lining the human airway tissues. When cleaved (R364), the protein "tails" on each side are free to adopt whatever conformation they want.
> 
> But for 364S, these two ends are no longer free to diverge from each other, which could drastically change the local conformation of the protein, leading to antibody evasion.
> 
> See: [cov-lineages/pango-designation#2180](https://github.com/cov-lineages/pango-designation/issues/2180)

thanks but here we have S:R346S not 364S. @ryhisner found something with that mutation at 364 yesterdaay but not this one.

**Comment by FedeGueli** [comment]
> Interesting, and agree with Jesse's summary. Possible that the 483 deletion could modulate impact of mutations at 486. We have yeast RBD DMS data in the [SARS-Cov-1 Urbani background](https://tstarrlab.github.io/SARSr-CoV-RBD_DMS/RBD-heatmaps_delta/), which likewise has a deletion at ~483 relative to SARS2 (depends on exact alignment where the deletion is placed). In our SARS1 data, R at 486 looks less deleterious for ACE2 affinity than it does in some of the SARS2 backgrounds -- a little bit worse binding than L486 or F486, but better than e.g. P486.
> 
> Obviously a lot more sequence differences in SARS-CoV-1 so many potential causes at play. We should have yeast RBD DMS data in BA.2.86 sometime in Jan/Feb if all goes well.

Thank you very much!

**Comment by FedeGueli** [comment]
![Schermata 2023-12-05 alle 09 37 43](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/512de854-599e-4a59-90cb-4e8bf9bd8e2e)
@tylernstarr sorry for bothering could you help reading it? the rbd is from Sars cov2 it seems to me, how i can see effect on Sars1 ? the heat level is the effect on Sars 1 rbd?

**Comment by FedeGueli** [comment]
> ![Schermata 2023-12-05 alle 09 37 43](https://private-user-images.githubusercontent.com/87669813/287975547-512de854-599e-4a59-90cb-4e8bf9bd8e2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NjU4NzAsIm5iZiI6MTcwMTc2NTU3MCwicGF0aCI6Ii84NzY2OTgxMy8yODc5NzU1NDctNTEyZGU4NTQtNTk5ZS00YTU5LTkwY2ItNGU4YmY5YmQ4ZTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA4MzkzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZDAyMDY2ZjJjZTVkMzhmNGZiMDkwZDYyMDA5MDFkNDEwNTI3OGY4ZWY3NjVlZTVhNDVjZTY1NzlhYzZmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SFqpplBv4kfAcDFvGuh7TM3oCekYmyi8qn9EV4P6gno) @tylernstarr sorry for bothering could you help reading it? the rbd is from Sars cov2 it seems to me, how i can see effect on Sars1 ? the heat level is the effect on Sars 1 rbd?

scratch that i selected Sars 1 now sorry!

**Comment by thiolist** [comment]
Sorry about my typo. I meant R346S (not R364S) in my previous comment.

**Comment by FedeGueli** [comment]
5 all branch , 4 without 486R

**Comment by FedeGueli** [comment]
it seems dead as today
