### ISSUE TITLE
XBB.1.5 sublineage emerged in Ecuador, Spain, Uk with orf9b:I5T and S:T20N (seen in Gamma) - 34 seqs- 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#134]
This xbb.1.5 sublineage has emerged in a branch of an undesignated XBB.1.5 with Orf9b:I5T (T28297C)
and further gained the infamous Gamma defining mutation S:T20N

Defining mutations:
**XBB.1.5  >> T28297C > C19140T, S:T20N  (C21621A)**

Gisaid query: **C19140T, C21621A,T28297C** 
finds 7  sequences all from May (Ecuador, Spain):
EPI_ISL_17683024, EPI_ISL_17683035, EPI_ISL_17683041,
EPI_ISL_17711720, EPI_ISL_17711724, EPI_ISL_17722405,
EPI_ISL_17726431

Tree:
![Schermata 2023-06-03 alle 01 08 08](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/07f9df1f-af07-4226-84a5-d4085ad6af9d)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2efd1_a76670.json?label=id:node_6981138

**Comment by aviczhl2** [comment]
Isn't XBB.1.5+T28297C being XBB.1.22?

**Comment by ryhisner** [comment]
I believe S:T20N should restore the glycan lost with the S:T19I mutation. pre-BA.2 lineages had an N-linked glycan at N17. I think the general rule is that an N followed by anything but P followed by either S or T creates the potential for a glycan, provided the geometry of and location of the residue is right. Since S:20-22 is very close to S:17-19, my guess is that T20N combined with T22 should also create a glycan, essentially restoring the one lost with S:T19I.
<img width="1415" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/6bfa9717-7e9d-498b-8d90-8698595cb626">

**Comment by BorisUitham** [comment]
One sequence: EPI_ISL_17683035 also has the combo spike_T19L instead of spike_T19I

**Comment by FedeGueli** [comment]
If no new seq will come next week i ll close this one.

**Comment by FedeGueli** [comment]
new batch from Ecuador it is around 5% there in June ping @corneliusroemer  i suggest to review this one.

**Comment by FedeGueli** [comment]
One more from Connecticut

**Comment by FedeGueli** [comment]
More sequence coming from SPain and a batch of 6 from England.

**Comment by FedeGueli** [comment]
@corneliusroemer this one after flying under the radar for a bit seems to have managed to start circulatinf both in Spain and England. Please take a look!
![Schermata 2023-07-27 alle 19 35 10](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/f11d73a2-133a-4f05-94c4-862a7c7fd5e0)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_23627_2a96c0.json?c=userOrOld&label=id:node_7043603

**Comment by FedeGueli** [comment]
![Schermata 2023-07-27 alle 19 36 50](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/88b2069d-fa44-4a9c-b6ae-15995d2883d5)
worth reviewing also the parental lineage with infamous Orf9b:I5T that has grown to 150 with 3 or 4 branches (one is S:T20N)

**Comment by FedeGueli** [comment]
3 more sequences from Uk . i will go proposing it.
