### ISSUE TITLE
Large usher artefactual branch attracting JN.1/2 seqs with no coverage around S:20

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#1347]
There seems to be a large artefactual branch on BA.2.86.1 but actually being JN.1/2, when investigated I found it attracts seqs with no coverage around S:20. 

@AngieHinrichs @yatisht
[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice17_genome_test_5370_5bae80.json?label=id:node_6851337)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/2f849c78-5d90-49c3-b730-af43fc24d566)

**Comment by FedeGueli** [comment]
Thank you! it messes up also counts of sublineage with 346/572

**Comment by AngieHinrichs** [comment]
I will take a look, thanks.  By the way, please don't tag Yatish in reports of bad branches -- he is a busy professor at UC San Diego now and while he and his group are the developers of UShER and matOptimize, they are not directly involved in the daily update of the UC Santa Cruz SARS-CoV-2 tree.  These kinds of problems are caused by sequencing issues and the remedy is to prune sequences and/or mask sites that are error-prone.  In general they are not bugs in the UShER software.  It is applying maximum parsimony to real-world imperfect data.  My job would be so easy if sequence data were perfect.  🙂

**Comment by FedeGueli** [comment]
> I will take a look, thanks. By the way, please don't tag Yatish in reports of bad branches -- he is a busy professor at UC San Diego now and while he and his group are the developers of UShER and matOptimize, they are not directly involved in the daily update of the UC Santa Cruz SARS-CoV-2 tree. These kinds of problems are caused by sequencing issues and the remedy is to prune sequences and/or mask sites that are error-prone. In general they are not bugs in the UShER software. It is applying maximum parsimony to real-world imperfect data. My job would be so easy if sequence data were perfect. 🙂

- Thank you please everyone read this. just tag only @angiehinrichs . cc @ryhisner @JosetteSchoenma @borisuitham @aviczhl2 @nkrmnzr @over-there-is @alurqu @c19850727  @krosa1910

**Comment by AngieHinrichs** [comment]
Some of those sequences have Ns from ~21610-21640 while others have a series of substitutions within the range 21610-21624 which I think are likely errors.  21610 was already masked in BA.2.86 by [previous request](https://github.com/sars-cov-2-variants/lineage-proposals/issues/606#issuecomment-1801095482).  So I'm going to mask all sites in 21610-21624 on the BA.2.86 branch as of today's build (2024-01-30).  Hopefully when it's done later today those sequences will be placed without the dubious mutations in that range.

**Comment by FedeGueli** [comment]
Thank you @AngieHinrichs !
