### ISSUE TITLE
USHER: KP.1.1 splitted in two and placed partially as a sublineage of KP.2

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1449]
Hi @angiehinrichs
i open an issue publicly cause these two lineages will likely be two of the new global dominant FLiRT lineages already from the next month,
KP.1.1 is misplaced as KP.2 sublineage when KP.1 still has its own S:R346T sublineage:
<img width="1153" alt="Screenshot 2024-03-18 alle 13 58 26" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/76a6af72-b9e2-49fc-ba66-0fc324c6814e">
<img width="1179" alt="Screenshot 2024-03-18 alle 13 58 44" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a034fee4-8d25-4ec8-947d-2f60dacec177">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_97f0_834d10.json?label=id:node_6945632

KP.1 + 346T with C11704T [that interestingly is also in JN.1.1.6 FLIRT (Branch 32 of #1089)]
<img width="1141" alt="Screenshot 2024-03-18 alle 13 59 36" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/34a5329d-557b-4303-bc28-ab8a1d261448">

**Comment by AngieHinrichs** [comment]
Thank you @FedeGueli !  Since JN.1.11.1 has a branch with only A24819G (S:K1086R; KP.1, 66 sequences), and a branch with only G22599C (S:R346T, KP.2, 82 sequences excluding KP.1.1), I don't have a way to tell usher/matOptimize that the new branch with both of those mutations should go on the smaller of the two equally parsimonious branches.  However, since each branch in question is now designated as a lineage, hopefully the lineage labels will cause sequences to get the correct lineage assignments despite the undesired placement of KP.1.1.  There are a few cases like that elsewhere in the tree.  

I see what you mean about some KP.1 branches acquiring G22599C, but it seems to follow other mutations that KP.1.1 does not have (C11704T like you said and G1820A).
