### ISSUE TITLE
LA.2 (FLiRI) sublineage with S:A942T and N:G243C  spreading in England (11)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1536]
LA.2 > C18814T, S:A942T (G24386A), C26058T, N:G243C (G29000T)

Query: G24386A, C26058T

Samples: 7 UK
EPI_ISL_19062702, EPI_ISL_19062710, EPI_ISL_19062718,
EPI_ISL_19069669, EPI_ISL_19069684-19069685, EPI_ISL_19069690,
Tree:
<img width="1177" alt="Screenshot 2024-04-26 alle 13 06 47" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d85a6bca-ee56-4ff8-b438-dac43848bf8b">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice2_genome_test_471cf_abe230.json?label=id:node_7049285

**Comment by ryhisner** [comment]
Cysteines in this region of N could have a real effect. The Delta branch with N:G215C eventually dominated over the other Deltas, and it was most likely due to G215C. It formed a disulfide bond in the N dimer, which is its standard form. That somehow made packaging much more efficient. There's a fantastic study on this, but I can't find it right now for some reason. 

I've seen a couple other mutations to C in this part of N—G238C is one, if I remember right.

**Comment by FedeGueli** [comment]
> Cysteines in this region of N could have a real effect. The Delta branch with N:G215C eventually dominated over the other Deltas, and it was most likely due to G215C. It formed a disulfide bond in the N dimer, which is its standard form. That somehow made packaging much more efficient. There's a fantastic study on this, but I can't find it right now for some reason.
> 
> I've seen a couple other mutations to C in this part of N—G238C is one, if I remember right.

Thank you @ryhisner when proposing i was thinking the same of N:G215C, that likely has been one of the top pandemic lineages for number of infections, and i think you are right there have been some lineages with other C in that region has popped up before.

**Comment by FedeGueli** [comment]
+2 (1 not shown on Gisaid) from Uk

**Comment by FedeGueli** [comment]
Not spreading at all
