### ISSUE TITLE
KP.3 with S:V213E [V>G213E] (70 seqs, USA, Canada, France, Spain, Sweden, Japan)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#1630]
**Defining Mutations:** `KP.3` > `T22200A (S:V213E)` _or `(G22200A/S:G213E)`_ > `C1420T`
**Query:** `C1420T, T22200A, C23039G`
**Earliest seq:** 2024-04-15 (`EPI_ISL_19140084`, Arizona, USA)
**Latest seq:** 2024-05-31 (`EPI_ISL_19193272`, Colorado, USA)
**Sampled Countries:** USA (13: NV/3; AZ/2; CA/2; UT/2; CO; MN; _GBW_ samples with travel history to: France and UK); Canada (1: BC)
<details><summary>Genomes: </summary>

for `lineages.csv` commit:
```
Canada/BC-BCCDC-715294/2024
USA/AZ-ASPHL-0784/2024
USA/AZ-ASPHL-0876/2024
USA/CA-CDPH-500137106/2024
USA/CA-GBW-GKISBBBC22631/2024
USA/CA-KP002332/2024
USA/CO-CDPHE-41933814/2024
USA/MN-MDH-41685/2024
USA/NV-CDC-QDX96893379/2024
USA/NV-NSPHL-24-S000839/2024
USA/NV-SNPHL-812816/2024
USA/UT-UPHL-240529433284/2024
USA/UT-UPHL-240531553114/2024
USA/WA-GBW-GKISBBBB26453/2024
```

epi_isl accessions:
`EPI_ISL_19101692, EPI_ISL_19140084, EPI_ISL_19174469, EPI_ISL_19175814, EPI_ISL_19175836, EPI_ISL_19183083, EPI_ISL_19184792, EPI_ISL_19188838, EPI_ISL_19191509, EPI_ISL_19191522, EPI_ISL_19193272, EPI_ISL_19197191, EPI_ISL_19199120, EPI_ISL_19199538`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3afd5_185f80.json?label=id:node_7000828
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/ac334a77-f6e7-4134-bfb0-e321eca93586)

**Trivia:**
- It's tweaking BA.2.86 basal `T22200G(S:V213G)` to `BJ.1/XBB`'s `T22200A (S:V213E)`, and kind of homoplastic on `KP.3` (at least 3 sub-branches now, those are under `KP.3.1` and `KP.3.3` respectively)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/82d15f7e-3113-44ad-a707-0c5542bdf411)

**Comment by FedeGueli** [comment]
Sorry ive missed this one.

**Comment by FedeGueli** [comment]
+3 from 3 different US States

**Comment by ryhisner** [comment]
Very interesting. The trend toward a more negatively charged NTD continues, even in KP.3, whose RBM is less positively charged than others due to Q493E. We see the same movement toward negative charge with R78X, H146Q, K147E, K182E, K182N, K182T, N185D, R190S, R190T, R214H, R237X, R273X, etc. On top of that, ∆S31 and R190S/T add glycans, which have negative electric charge. There are some exceptions (W64R, W152R, W258R, P272H), but apart from Q183H in LB.1, which modestly increases positive charge, they are less common and less successful than the negative-charge mutations. 

This is all on top of the existing negative-charge changes in the JN.1 NTD, which include R21T, ∆H69, H245N (which also adds a glycan), and A264D. I don't know the reason, but something's happening here.

**Comment by FedeGueli** [comment]
+3 US, Can and GBW

**Comment by FedeGueli** [comment]
Big batch from California now 41. One gbw sample from France.

**Comment by FedeGueli** [comment]
please propose it

**Comment by aviczhl2** [comment]
Designated KP.3.5
