### ISSUE TITLE
MD.1 (FLiRT) + S:F58Y,S:S59L (12, 8 countries) emerged in Philippines

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1671]
transferred back from https://github.com/cov-lineages/pango-designation/issues/2680

In the batch uploaded today from Philippines i noticed a weird a double AA mutation in the spike in a row.
Being in an area under pressure for convergent evolution and sampled in a very undersampled are better to track it for a bit

Defi ning mutations:
MD.1 >> ORF1a:Y182H (T809C), T10999C, S:F58Y (T21735A), S:F59L (T21737C),G28798A
Query:T809C, T10999C,
Samples: 3 ( 4 on Usher from England, US, Philippines and Australia)
IDs:EPI_ISL_19096194, EPI_ISL_19180401, EPI_ISL_19227260,
Tree:
<img width="1164" alt="Screenshot 2024-07-02 alle 11 54 14" src="https://github.com/cov-lineages/pango-designation/assets/87669813/798794a8-0562-459a-bc6b-d170bad81f53">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_134e9_3caa70.json?c=gt-S_58,59&gmax=25384&gmin=21563&label=id:node_7159421

**Comment by FedeGueli** [comment]
@ryhisner spotted a quite long insertion at S:215 it is Spike_ins215AGERWR (Query)

**Comment by ryhisner** [comment]
> @ryhisner spotted a quite long insertion at S:215 it is Spike_ins215AGERWR (Query)

Yeah, it's in the sequence from the Philippines. Sometimes sequences from the Philippines are unreliable, but I think this insertion is real for a few reasons:

1. It's in a location known for insertions.
2. Though there is dropout elsewhere in the sequence, there is no dropout in the neighborhood of this insertion.
3. The insertion is loaded with guanines. 10/18 nucs are G's here. I've noticed that, despite G being much less common than A and T throughout the genome, it is enormously overrepresented in insertions. I still don't know the reason for this. Perhaps it's a well-known principle that I'm just not aware of. My only idea is that because G can form strong bonds with C in the secondary RNA structure (stronger than A-T bonds due to having three hydrogen bonds instead of two) and because it can also form non-Watson-Crick bonds with T, which is the most common nucleotide in the viral genome, insertions that are full of G's may, on average, better preserve secondary RNA structure.

The exact insertion, according to both GISAID and Nextclade, is S:ins215_AGERWR, or ins22207_GCTGGAGAGAGATGGCGG.  

<img width="1241" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/970cb82d-6e08-4036-a90b-b1a8984bc25f">


Incidentally, another insertion that appeared in two KP.2.3 sequences today (and in one or two earlier sequences) is S:ins182_ERA, and sure enough, G's are overrepresented here as well, even in the same ratio as the above insertion, with 5/9 nucs being G's. 

Here the insertion is ins22108_GAGAGAGCG.

<img width="1378" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/be06558b-c9bc-439a-afaa-e9d988ab967b">

**Comment by FedeGueli** [comment]
Thank you @ryhisner

**Comment by FedeGueli** [comment]
+1 NY

**Comment by FedeGueli** [comment]
+1 Texas, even if still quite old ones

**Comment by FedeGueli** [comment]
+2 Qatar via GBW and Maryland

**Comment by FedeGueli** [comment]
+2 France, Canada

**Comment by FedeGueli** [comment]
+1 Australia

**Comment by FedeGueli** [comment]
+1 France

**Comment by FedeGueli** [comment]
12 Germany

**Comment by FedeGueli** [comment]
3 only samples in July closing it

**Comment by FedeGueli** [comment]
Designated MD.1.2 via https://github.com/cov-lineages/pango-designation/commit/c309913c4173e0e655f7e8e1b2cd503a2e80bef3
