### ISSUE TITLE
JN.1.16 got S:Q493E (18 seqs, 10 countries including Taiwan and China, with further S:S31P(11) and then 346T(1) after triple nuc mutation Orf7a:F59K

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#1702]
Jn.1.16 seems to have acquired S:Q493E in Taiwan

Defining mutations:
Jn.1.16 >> A532G, **Orf1a.G400S** (G1463A). > **Orf7a:F59K** (T27568A, T27569A, T27570A) > **S:Q493E** (C23039G) >> **N:P279S** (C29108T) > **S:S31P** (T21653C) 
Query: NEW  : A532G,C23039G,T3565C 
[Old queries: C23039G, C29108T, T27570A by @aviczhl2  or  A532G, G1463A,C4543T initial]
Samples: 18 (17 with S:Q493E) 
Tree (Updated on 08-10):
 <img width="1154" alt="Screenshot 2024-08-10 alle 08 06 26" src="https://github.com/user-attachments/assets/977a85d0-93ac-45ec-b873-33cc4aa8d719">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_test_5ada8_700150.json?f_userOrOld=uploaded%20sample&label=id:node_7234797

One of the last samples has also S:R346T spotted by @aviczhl2 
Query for the S:R346T branch: C23039G, C29108T, T27570A,G22599C (by @aviczhl2 )
 
 
 [Thx @ryhisner Ryan for highlighting the belgian sample belonging to the parent of this lineage]

**Comment by ryhisner** [comment]
ORF7a:F59K is a really bizarre mutation—it's a triple T->A mutation. T->A is the third-rarest type of nuc mutation, so there's no way this happened stepwise. It's happened numerous times independently throughout the pandemic, so I have no doubt that it's real. There are now 50 sequences total with ORF7a:F59K that I think are legit.
<img width="1092" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e825d057-a3d4-4a55-9423-1f6fa585165f">


There are other double-A or triple-A mutations but they usually fit one of a number of patterns, the main ones being TRS-like motifs and recombination with the region just before the N start codon. This one doesn't fit either pattern. However, with it, 25764-25774 makes for a perfect reverse complement of an 11-nucleotide stretch in NSP6 (11131-11141). I regard stretches of 8-9 nucleotides as likely being coincidental, but 11 nucleotides is unlikely to be a coincidence. 

<img width="1506" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/582217aa-1f5b-44fe-a610-2fe65ee3b21b">

So my guess is that this triple-T->A mutation is due to recombination with this this region of NSP6, though I don't feel overly certain about that. 

It's also worth noting that there's a second stretch of nucleotides, 7593-7602, that forms the ORF7a:F59K region forms a perfect reverse complement with over a 10-nucleotide stretch, which again is more than you'd expect to find by coincidence. 
<img width="1263" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/cf804169-1137-45f2-8880-a62b90501bc5">

**Comment by FedeGueli** [comment]
thank you Ryan!

**Comment by FedeGueli** [comment]
+1 Canada

**Comment by FedeGueli** [comment]
Query updated: C23039G, C29108T, T27570A

**Comment by FedeGueli** [comment]
3 more, very recent,  from Taiwan spotted by @ryhisner

**Comment by aviczhl2** [comment]
One of the Taiwan seqs also have S:R346T. It seems that lineages with both 346T and 493E are emerging these days.

**Comment by FedeGueli** [comment]
> One of the Taiwan seqs also have S:R346T. It seems that lineages with both 346T and 493E are emerging these days.
> 
> Query: C23039G, C29108T, T27570A,G22599C

thx updated.

**Comment by FedeGueli** [comment]
+1 Japan

**Comment by FedeGueli** [comment]
+2 Singapore

ping @corneliusroemer

**Comment by aviczhl2** [comment]
+1 GBW from Italy. 
Seems that it first gets S:S31P(Query: C23039G, C29108T, T27570A,T21653C) then S:R346T.

**Comment by FedeGueli** [comment]
there are two more among the GBW samples. so it is 15 i am checking the query

**Comment by FedeGueli** [comment]
Got it: new query A532G,C23039G,T3565C finds 18

**Comment by aviczhl2** [comment]
Better propose it in main repo?

**Comment by FedeGueli** [comment]
transferred to https://github.com/cov-lineages/pango-designation/issues/2726

**Comment by FedeGueli** [comment]
Designated JN.1.16.4 and MT.1 via https://github.com/cov-lineages/pango-designation/commit/f7249dc8559ccbd3a4147ee9c4464993a4e1e375
