### ISSUE TITLE
XBB.1.5 with ORF7a:T120I, ORF1a:L2869F, S:E554A, S:T478R [40 seqs, 9 countries]

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#175]
**Defining Mutations:** _On top of XBB.1.5's T10204C branch_ > C27752T (ORF7a:T120I) > G8872T (ORF1a:L2869F), A23223C (S:E554A) > C22995G (S:T478R, on top of C22995A)
**Query:** G8872T, C27752T, A23223C, C22995G
**Earliest seq:** 2023-03-27 [EPI_ISL_17480728, France]
**Latest seq:** 2023-05-23 [EPI_ISL_17736892, Italy]
**Sampled Countries:** Italy (14), France (3), Austria (2), South Korea (1), Spain (1) USA (1, Minnesota)
<details><summary>Genomes: </summary>
EPI_ISL_17433511, EPI_ISL_17480728, EPI_ISL_17485332, EPI_ISL_17502271, EPI_ISL_17526212, EPI_ISL_17589783, EPI_ISL_17612067, EPI_ISL_17612071, EPI_ISL_17612088, EPI_ISL_17651696, EPI_ISL_17651721, EPI_ISL_17651724, EPI_ISL_17659118, EPI_ISL_17679551, EPI_ISL_17681009, EPI_ISL_17715320, EPI_ISL_17722085, EPI_ISL_17726244, EPI_ISL_17736892, EPI_ISL_17769664, EPI_ISL_17778878, EPI_ISL_17782185
</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_303de_8049c0.json?c=gt-S_478&f_userOrOld=uploaded%20sample&label=id:node_6833553&showBranchLabels=all

C27752T (ORF7a:T120I) parent branch overview
![ORF7a_T120I](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/b667a3e4-e87c-463f-934e-84f87fdc6c80)

details:
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/dbf012f7-53b4-49ad-b5c5-009e28e50289)

**Trivia:**
- Undesignated parent branch ORF7a:T120I has about 400-550 ish sequences (query: T17124C, T10204C, C27752T). It is one of the definition mutation of Delta (and delta-3'-tip-derived XBC), may have to do something related to downstream ORF7b TRS (not sure about this, maybe @ryhisner could shed some light :)
![27752](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/6bcdcc22-cba5-464e-a25b-a37c06b1bc99)
- Also noted that 2 of Italian mini-saltation sequences, EPI_ISL_17722085 and EPI_ISL_17659118 could have reversions: S:N405D and S:S408R, the former is expected to have extra immune escape on current XBB background, but hard to track due to potential dropout.

**Comment by ryhisner** [comment]
@NkRMnZr, officially, there is no ORF7b TRS; it's supposed to be expressed only due to "leaky scanning," i.e., the ribosome skipping over the ORF7a start codon. However, I suspect the AAAAGAAA sequence just before ORF7b functions as a weak TRS. ORF7a:T120I isn't located in that quasi-TRS, but it's just downstream, and C27752T increases the already substantial extended homology on the 3' end. I'd never noticed that before, so thanks for spotting this!

<img width="1398" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/9b75564d-64e4-44ee-b36d-7f09928b35d2">

**Comment by FedeGueli** [comment]
It seems fast lets wait next week to evaluate if proposing it.
