### ISSUE TITLE
KP.3.1+S:C1243F (9 sequences, 3 countries)

### ISSUE THREAD

**Issue by Clrs17** [sars-cov-2-variants/lineage-proposals#1847]
KP.3.1 with S:C1243F (G25290T)
Seems to have already diverged into two sub-branches, one with ORF1a:P309L, ORF1a:A1812S, ORF1b:P1664S and the other with ORF1b:Q813H, ORF1b:Y1464C.
Earliest sequence: EPI_ISL_19296880 (Spain, 2024-05-20)
Latest sequence: EPI_ISL_19286252 (USA. 2024-07-02)
possible GISAID query: G15372T, A19722G, G25290T
![image](https://github.com/user-attachments/assets/71488e65-e1b6-4e45-904a-71c19b804afb)
It seems to have been in transmission for a while.

**Comment by FedeGueli** [comment]
Thx @Clrs17 for spottin g, the lineages you re proposing are very interesting but i suggest you to look at collection dates: unless it comes from a very undersampled area when you don't see any sample from July maybe it is worth to tracking privately until some more recent will come , because no july samples to me points at dying or low circulating lineages.

**Comment by FedeGueli** [comment]
S:C1243F was in BF.7.14 the second biggest lineage of the huge chinese 22-23 wave.

**Comment by FedeGueli** [comment]
9 but all old samples
