### ISSUE TITLE
Double node bug for KP.3.1.1

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#2036]
@AngieHinrichs, again the double node bug of usher happens, this time on KP.3.1.1

There seems to be a new branch starting from JN.1.11 and gets T22928C, G15372T, C7113T, C23039G, T21738C, C12616T, A13121T, C21738T, A19722G, resulting in exactly the same mutation of KP.3.1.1(just in different order and introduces a flip-flop), effectively creates a double node for KP.3.1.1 and attracting KP.3.1.1 seqs. 

This bug is harmful for tree construction and needs urgent analyse and fix. 

[usher](https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice165_genome_test_534cf_684390.json?label=id:node_5463256)

![image](https://github.com/user-attachments/assets/7242fedc-3012-40c8-98f5-7eaf5acffeb7)

**Comment by FedeGueli** [comment]
Already highlighted to @angiehinrichs last week.

**Comment by Over-There-Is** [comment]
And both JN.1.16 and JN.1.18 are placed on a KP.2 flip flop branch now.

**Comment by FedeGueli** [comment]
> And both JN.1.16 and JN.1.18 are placed on a KP.2 flip flop branch now.

cc @angiehinrichs

**Comment by FedeGueli** [comment]
Solved by @angiehinrichs :
<img width="1144" alt="Screenshot 2024-09-17 alle 11 23 34" src="https://github.com/user-attachments/assets/3ed1be38-0adc-424e-b577-135a158d6332">
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_50279_949320.json?label=id:node_11659193

@Over-There-Is open a separate issue fro the KP.2/Jn.1.18 thing please

**Comment by AngieHinrichs** [comment]
Last night I did a prune & re-optimization on the 2024-09-16 tree, to make an intermediate tree that will be used as the basis of today's 2024-09-17 build.  That fixed the following problems in the intermediate tree, and hopefully will still be fixed in the 2024-09-17 tree when that is ready later today:
* KP.1.1.3 on branch with multiple flip-flops
* split MC.1
* split KP.2
* split KP.3
Unfortunately it was not enough to fix the problem of JN.1.16 / JN.1.18 being on a branch with reversions from KP.2 -- that branch found a different branch with fewer reversions (but still some reversions), that I will also need to prune in another attempt.
