### ISSUE TITLE
BN.1.3.1 mini saltation (2 seq. Italy) 

### ISSUE THREAD

**Issue by agamedilab** [sars-cov-2-variants/lineage-proposals#228]
Proposal for a sublineage of BN.1.3.1
Earliest sequence: 23.01.2022 (Italy)
Countries detected: Italy

Defining mutations:
nuc	unique	C4763T, C13536T, T22385C, T22928C, G23015A, C27595T, C28550A
nuc	homoplasies	T21752A, G22203A, C29250T
ORF1ab	unique	H1500Y
S	unique	F275L, F456L, G485S
S	homoplasies	W64R, R214H
ORF7a	unique	P68S
N	homoplasies	P326L

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/812a4ea9-bbed-42ff-879c-0d244a7d124e)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2dc09_2da090.json?c=gt-S_64

![grafik](https://github.com/sars-cov-2-variants/lineage-proposals/assets/102166254/e0181b7e-68bb-4c39-a0ff-e3125c127b83)

EPI_ISL_17032070
EPI_ISL_17819921

Gisaid query: C4763T, C13536T, T22928C

**Comment by FedeGueli** [comment]
The recent  sequence has also S:L455W and S:F486S

This should be kept monitor, if it is not a single patient as we could think it something very interesting

![Schermata 2023-06-21 alle 15 18 39](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/980f98af-3988-4864-a4ff-5c67f58cd865)

**Comment by ryhisner** [comment]
I remember the first sequence from this one back in January because it was one of the only sequences I've ever seen with S:F464Y. It seems that one, along with a handful of ORF1ab mutations, has reverted. 

There are two ORF9b mutations here as well, including one that's becoming a chronic classic—ORF9b:D89E, which is also found in BA.2.3.20. On the two branches leading to this one, 22/26 (85%) nucleotide mutations are non-synonymous, a very typical high number for chronic branches like this.
