### ISSUE TITLE
Very Weird Seemingly Recombination Sequence

### ISSUE THREAD

**Issue by krosa1910** [sars-cov-2-variants/lineage-proposals#24]
i think I discovered a very weird BA.2.75* x XBB* thing, it is just one sequence, but I want to get the mystery out of it.

EPI_ISL_17561476

It has mutationnfeatures for me to consider it as a recom: for example, it got the iconic S:445P and that is considered a hallmark of XBB, yet it also contain S:213G which is highly indicative of non-XBB traits. 

The triple mutation series K147E,W152R, F157L is very definitely an BA.2.75* trait, so I guess that this forms the second parent of this lineage. So I claim this to be some BA.2.75* x XBB*, this itself is not very weird/exciting. 

The breakpoint could be quite broad, as I could only cut it down to somewhere between S:G257S/G22331A that comes from BA.2.75* and C22664A that is quite rare in BA.2.75* but mostly common in XBB*. 

What seems to be troubling me is that this lineage just lacks a lot of mutations to put its parents under popular branches. For example, it does not have the typical Orf8:G8*, that means it is likely not from XBB.1* ( there does exist two XBB.1* branches, but not that significant), while XBB.2.3* are excluded because the lack of Orf7:A13L. So there simply are not a lot of choices for the XBB parent.

While for the BA.2.75* branch it is also troublesome, on one hand, Orf1a: L3829F and the fact the lineage is from Australia is strongly indicative of FK*, but it simply lacked too much mutations from general CH* clade such as G18583A and C3857A. Two other popular choices: BR and BN are discarded for similar reasons as they does not fit the Orf1ab mutations.

So I would like to ask you guys for help at figuring what this is.

@ryhisner @FedeGueli @corneliusroemer

**Comment by corneliusroemer** [comment]
Nextclade pic (next time if you post add it so that one has an idea what the mutations are)
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/25161793/236704053-9ec350d0-2370-4a9e-acda-0ffcfbf05429.png">

**Comment by corneliusroemer** [comment]
One donor is quite likely FK.1.1 (CH.1.1 sublineage)

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=%5B6-of%3AC10507T%09%2CC11416T%09%2CC21811T%09%2CG23401T%2C%09A23416T%2C%09T25461C%2C%09C27804T%2C%09G28374A%2C+C28706T%2C%09A29079G%5D&

so the question is only where the rest comes from and where the breakpoints are

<img width="1824" alt="image" src="https://user-images.githubusercontent.com/25161793/236704218-397d5a46-0c36-4bf9-a263-6e936d003d5e.png">

**Comment by JosetteSchoenma** [comment]
I saw this one yesterday. From NSW. It is on my list to have a better look at. 

Thank you, @krosa1910.

**Comment by krosa1910** [comment]
> I saw this one yesterday. From NSW. It is on my list to have a better look at.
> 
> Thank you, @krosa1910.

What do you propose its parent lineage could be?

USHER put it to be BY.1, seemingly laughable at first, but I understand the logic that it lacks a lot of early definition of major BA.2.75.x (x=3,4,5), so to not mark a reversion, it decided to adopt the very broad BA.2.75.6 definition. 

i am also looking at possibility that this comes from a more complex recombination system. I mean for example, suppose that L3829F comes from xbb.1.9 or even BQ, however, that is hard to do and I don't get a lot of progress here.

**Comment by corneliusroemer** [comment]
Here's the closest match for private mutations: FK.1.1

So that should help figure out where the other donor should be:

<img width="2525" alt="image" src="https://user-images.githubusercontent.com/25161793/236704359-fc83c1e7-e79d-43bc-81a4-5b7d788a7831.png">

This is with respect to BA.2 (the dataset is 21L)

Weirdly, no mutations in the stretch 0-4.5k, and 5.1-9.8k -> looks like dropout/artefact?

10204C is XBB.1, 17124C is classic XBB.1.5 hallmark

Spike has some XBB.1.5-like signs

So would have to be a complex FK.1.1-XBB.1.5 recombinant:

FK.1.1 - 405/1465 - XBB.1.5 - 4586 / 5183 - FK.1.1 - 11750/12444- then it doesn't really fit , Spike is FK.1.1 up to S:257, then it is XBB.1.5, but afterwards it looks like FK.1.1 again, after say 613H

So at least 4 breakpoints, even then it doesn't fit super well. So I'd say I'm not convinced this is a clean recombinant - maybe some contamination.

Top is sequence in question, below are the two donors that would fit best:
<img width="2545" alt="image" src="https://user-images.githubusercontent.com/25161793/236704850-05b9cc63-54a3-45fc-87b9-b49cd72cf7d6.png">

**Comment by FedeGueli** [comment]
It could FK.1 for the presence of  ORF1a:L3829F and  S:D215G, but it lacks some of the defining of FK.1.1 in the orf1a as ORF1a:A1060T while it has the defining of FK.1.1 Orf9b:G31R/N:G34E at the 3'end of the genome. 

While for the XBB.1 side i ma for XBB.1.5 having it T17124C and T10204C . I am not sure it is real.

**Comment by corneliusroemer** [comment]
FK.1.1 is a very likely big donor, it coincides in time and space with where this was sequenced. It's undoubtedly involved due to overlap in private mutations.

XBB.1.5 is also very likely involved. Maybe, there's another donor, but 3-way recombinant is much less likely a priori.

**Comment by krosa1910** [comment]
How much of it is seriously not FK.1.1? ( I guess I would like to ask that problem) Now I doubt that it could be a heavily polluted sample with random intrusion of XBB.1.5 fragment on the larger backbone of FK.1.1.

**Comment by corneliusroemer** [comment]
@krosa1910 look at the Nextclade pic, it shows pretty much all you need, you can just see where the breakpoints are by looking for matching segments

**Comment by JosetteSchoenma** [comment]
Sorry @krosa1910 , bedtime here. On my notes I stopped at FK.1/XBB, which means I need a better look. I will join the discussion tomorrow.

**Comment by aviczhl2** [comment]
> i am also looking at possibility that this comes from a more complex recombination system. I mean for example, suppose that L3829F comes from xbb.1.9 or even BQ, however, that is hard to do and I don't get a lot of progress here.

L3829F can occur independently. It is very common in chronic saltations, and can also come from unnamed sub-branches of any variants.

**Comment by JosetteSchoenma** [comment]
Oke. I had a look. I think it is either a co-infection or contamination. I found an XBB.1.5 (EPI_ISL_17561470) and an FK.1.1 (EPI_ISL_17561499) that together account for all mutations (with some N's that are accounted for by a 4th sample (the FK.1.1 on top))!

The 3 samples are from the same lab in NSW and the same date. I count around 10 breaking points, which seems way too much for a recombination. Since it says the lab is in a hospital, I think we cannot rule out a locally infected patient simultaneously by 2 other patients either.

Nextclade, mutations compared to BA.2:
![image](https://user-images.githubusercontent.com/94831035/236828385-f6fa81a8-d84d-404a-9128-92fb3078272f.png)
![image](https://user-images.githubusercontent.com/94831035/236828522-71e4d8ec-2bae-4252-bbd5-7f40e32ef83f.png)

Query to see if it spreads: C4586T, C5183T, T10204C, C10507T

**Comment by FedeGueli** [comment]
Still no new seqs with C4586T, C5183T, T10204C, C10507T closing it for now
