### ISSUE TITLE
Upward trend of Orf8:S67F in XBB*

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#251]
Orf8:S67F is a common mutation. Lots of XBB* has this branch.

I just noticed that there's a stable upward trend of the proportion of Orf8:S67F inside XBB*.  It is a sum of seqs with orf8:S67F on all XBB* branches and not co-occurence effects, and as it appears everywhere in the world it is not  asymmetric submission delay effects. 

Which is quite difficult to understand given the G8* truncation. 

<img width="1210" alt="Screenshot 2023-06-26 at 01 09 42" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/a9108088-544b-435d-bca8-6381026b4ab9">

**Comment by FedeGueli** [comment]
i think @ryhisner have studied this mutation a bit deeper than the rest, maybe he wants to share its finding here.

**Comment by FedeGueli** [comment]
cc @ryhisner do you want to share your findings on this mutation?

**Comment by ryhisner** [comment]
I don't think this mutation has any fitness benefits, which seems more obvious than ever now that it occurs behind a stop codon. Instead, I think it is in an extraordinarily favorable position for a C->T mutation to occur through APOBEC3 deamination. 

APOBEC3 is a host protein that causes C->T mutations through deamination of cytosine. It's known that some nucleotide contexts are much more favorable than others for this mutation. ORF8:S67F has a perfect nucleotide context since it's surrounded by T's or A's. Furthermore, in the secondary RNA structure, nucleotides that are unpaired and at the end of stem-loops are far more likely to be subject to C->T deamination. C28093 is unpaired and located at the end of a long stem-loop in the secondary RNA structure according to the only map of secondary RNA structure I've ever located. 
<img width="1475" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/0d384bb3-f8e6-4700-a529-578d9156989d">

<img width="853" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/ef7c41cd-1fdc-43a3-b861-47f9f5c06f07">





Here's a figure from another study that made a graph for all 16 possible nucleotide contexts for each type of transition mutation. C->T mutation contexts are the light blue bars. You can see that a context of TCT is extreme favorable. 




<img width="993" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/ebb59494-f2ed-434e-a041-e196225f8fd3">
