### ISSUE TITLE
XBB.1.9.2 with S:A344T and S:R403K (36 seqs) with a further sublineage that acquired S:S494P and S:A701V (18)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#346]
This is different from the one with the same combo 344-403 proposed in #57 

Defining mutations:
XBB.1.9.2 >> T16548G > G21255T, S:A344T (G22592A) then S:R403K that occured sparsely in the tree:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/lineage-proposals-346.json?branchLabel=Spike%20mutations&label=id:node_6711312
![Schermata 2023-07-20 alle 10 21 45](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/e9d50c3a-a2dc-404f-add1-ee4cf750d625)
(EDITED thx to @AngieHinrichs 

Gisaid query:  G22592A  ,T16548G

Samples:
hCoV-19/Germany/BW-RKI-I-1130697/2023\|EPI_ISL_17469433\|2023-03-29
Germany/BW-RKI-I-1130697/2023\|EPI_ISL_17469433\|2023-03-29
hCoV-19/Germany/BB-RKI-I-1136867/2023\|EPI_ISL_17964602\|2023-06-14
hCoV-19/New_Zealand/ESR-YA3735/2023\|EPI_ISL_17961859\|2023-06-20
hCoV-19/Austria/AGES-1140218/2023\|EPI_ISL_17881173\|2023-06-20
Austria/AGES-1140218/2023\|EPI_ISL_17881173\|2023-06-20
hCoV-19/USA/NY-NYULH-15211/2023\|EPI_ISL_17859849\|2023-06-15
USA/NY-NYULH-15211/2023\|EPI_ISL_17859849\|2023-06-15
hCoV-19/Spain/CT-HUGTiP-H4R140/2023\|EPI_ISL_17766036\|2023-05-30
Spain/CT-HUGTiP-H4R140/2023\|EPI_ISL_17766036\|2023-05-30
hCoV-19/Germany/BY-RKI-I-1136837/2023\|EPI_ISL_17964573\|2023-06-19
hCoV-19/Germany/BY-RKI-I-1136831/2023\|EPI_ISL_17964567\|2023-06-14
hCoV-19/Germany/BY-RKI-I-1136688/2023\|EPI_ISL_17950466\|2023-06-12
Germany/BY-RKI-I-1136688/2023\|EPI_ISL_17950466\|2023-06-12
hCoV-19/England/PHEC-YYE3RP8/2023\|EPI_ISL_17731127\|2023
England/PHEC-YYE3RP8/2023\|2023-05-17
England/PHEC-YYE5JSM/2023\|2023-06-13
hCoV-19/England/PHEC-YYE5JSM/2023\|EPI_ISL_17838179\|2023-06-13
hCoV-19/England/PHEC-YYE4Z6X/2023\|EPI_ISL_17813155\|2023-06-01
England/PHEC-YYE4Z6X/2023\|2023-06-01
hCoV-19/England/PHEC-YYEA518/2023\|EPI_ISL_17721719\|2023-05-08
England/PHEC-YYEA518/2023\|2023-05-08
hCoV-19/Austria/AGES-1140273/2023\|EPI_ISL_17881073\|2023-06-19
hCoV-19/Austria/AGES-1139913/2023\|EPI_ISL_17827065\|2023-06-14
Austria/AGES-1140273/2023\|EPI_ISL_17881073\|2023-06-19
Austria/AGES-1139913/2023\|EPI_ISL_17827065\|2023-06-14
USA/AZ-ASPHL-1546/2023\|EPI_ISL_17783179\|2023-05-24
USA/KY-CDC-QDX80414892/2023\|OR075710.1\|2023-05-12
USA/AZ00181318/2023\|OR119891.1\|2023-05-24
hCoV-19/USA/KY-CDC-QDX80414892/2023\|EPI_ISL_17852555\|2023-05-12
hCoV-19/USA/AZ-ASPHL-1546/2023\|EPI_ISL_17783179\|2023-05-24
hCoV-19/Canada/ON-PHL-23-25172/2023\|EPI_ISL_17764656\|2023-05-27
Canada/ON-PHL-23-25172/2023\|EPI_ISL_17764656\|2023-05-27
hCoV-19/USA/MD-CDC-QDX80689204/2023\|EPI_ISL_17855278\|2023-05-19
USA/MD-CDC-QDX80689204/2023\|OR099464.1\|2023-05-19

EDITED
Please note that a mini branch of this one gained further S:S494P and S:A701V now has grown to 17 seqs
 https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/lineage-proposals-346.json?branchLabel=Spike%20mutations&label=id:node_6711312
![Schermata 2023-07-20 alle 10 23 21](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/18c9ee35-bf17-4776-bb16-79b37314d88c)

Gisaid query for this sublineage : C335T, T16548G, G21255T

**Comment by FedeGueli** [comment]
20th sequence came from Denmark.

**Comment by FedeGueli** [comment]
5 new samples  : 3 from Germany one from NY and one from Uk ( caught by US airport surveillance)

**Comment by FedeGueli** [comment]
@corneliusroemer  @angiehinrichs did u see this one? it also has the combo 344-403 and it is also messed! maybe something with that combo??

**Comment by corneliusroemer** [comment]
I'm aware, it's part of the same 344-403 "issue".
My gut feeling is 344-403 arose once, ax twice. Will designate irrespective of Usher cleanliness if this haplotype keeps growing.

**Comment by AngieHinrichs** [comment]
Yes, this is the branch I mentioned the other day, where the two child branches with 22770A probably could be unified by prune/reopt/replace.  I believe this is distinct from #57 because of the other mutations found on the respective branches.  And I don't see how the other issue's child branches with G22592A (changing S:344 to a _T_) and C22593T (changing S:344 to a _V_) could be a "single occurrence", unless we're just seeing artefacts.  I have not checked for nearby indels but those have caused flaky "substitutions" before.

**Comment by corneliusroemer** [comment]
This should help figure things out, it's snipit with XBB.1.9.2 as reference.

I think there are indicators of having 403 occurring twice, and also 344T occurring twice. In total there seem to be 3 lineages .
![snp_plot](https://github.com/sars-cov-2-variants/lineage-proposals/assets/25161793/23b7bdc2-da2d-4f01-8998-e1312ca20ff3)

**Comment by FedeGueli** [comment]
Thx @AngieHinrichs and @corneliusroemer for looking into this!

**Comment by corneliusroemer** [comment]
Still not quite clear what and how to designate - especially as Usher is going to differ from what a careful analysis suggests. Let's wait a few more days for more sequences.

**Comment by AngieHinrichs** [comment]
Thanks @corneliusroemer, the snipit is very helpful since it shows several things clearly:

* a lot of Scotland sequences with C22593T (S:A344V) have N or R at 22770, so pruning and replacing those should clean up the C22593T branch which currently has multiple nodes with G22770A (S:R403K), but really pretty much all of those sequences should show 22770A as far as I can tell.
* there's strong support for two separate occurrences of G22592A and G22770A: one with C4686T, C13767T, A16373G and C29347T, and the other with T16548G and G21255T instead -- except for 5 sequences that have C4686T, C13767T, A16373G and C29347T, *and* G21255T, but not T16548G, so they could be either a two-breakpoint recombinant of those two branches or an independent gain of G21255T after C4686T, C13767T, A16373G and C29347T.
* The two G22592A branches each have some 22770Ns, and can be cleaned up.

The 2023-07-19 build should have 22770 all cleaned up.  Then I think the UShER tree will be doing about as well as a tree (as opposed to a graph) can do.

The 5 sequences that look like either a recombinant or independent G21255T to me:
```
USA/KS-CDC-VSX-A348335/2023|OR016338.1|2023-05-04
USA/MI-CDC-LC1045724/2023|OR252205.1|2023-06-28
USA/MI-CDC-LC1045721/2023|OR252207.1|2023-06-28
USA/MI-CDC-LC1045719/2023|OR252206.1|2023-06-28
USA/MO-CDC-QDX80414736/2023|OR075731.1|2023-05-12
```

**Comment by corneliusroemer** [comment]
Thanks a lot for writing this all up @AngieHinrichs - this is exactly what I concluded yesterday but didn't write up here. We seem to have in total 3 lineages + 1 extra recombinant. Not necessarily all worth designating, let's see which ones grow over the next few days.

**Comment by AngieHinrichs** [comment]
Cleaned up in 2023-07-19:
<img width="1382" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/186983/bb60d343-87a8-420e-bf78-3944cff8b146">
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/lineage-proposals-346.json?branchLabel=Spike%20mutations&label=id:node_6711312

**Comment by FedeGueli** [comment]
> Cleaned up in 2023-07-19: <img alt="image" width="1382" src="https://user-images.githubusercontent.com/186983/254781900-bb60d343-87a8-420e-bf78-3944cff8b146.png"> https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/lineage-proposals-346.json?branchLabel=Spike%20mutations&label=id:node_6711312

Thanks @AngieHinrichs !! @corneliusroemer i suggest to designate the sublineage with 494/701 seems really fast

**Comment by FedeGueli** [comment]
One more sample from Scotland (with all 4 spike mutations of the sublineage of the main lineage proposed here)
