### ISSUE TITLE
Today's Usher build seems to be calling XBB.1.5 as XBB.1

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#40]
The main branch has S:486P and all sub-branches are XBB.1.5.x, however usher identifies the main branch as XBB.1. @AngieHinrichs

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice34_genome_16c3a_b51b80.json)

<img width="1398" alt="Screen Shot 2023-05-10 at 23 56 07" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/df255d83-6a8a-4250-bd60-ab2e26872172">

**Comment by AngieHinrichs** [comment]
I'll take a look, thanks!

**Comment by AngieHinrichs** [comment]
This is really strange -- it looks like matOptimize created a new child of XBB.1 > G27915T > T17124C with T23018C instead of moving the branch's children onto the existing XBB.1 > G27915T > T17124C > T23018C node.  There should not be two children of a node with the same mutation (T23018C) but there are now, and only one of them was annotated as XBB.1.5 (the new node with only a few thousand samples, not the main XBB.1.5 node into which they should have been moved).  I will send a test case to @yceh, the author of matOptimize.  In the meantime I will see if I can fix it by running `matUtils extract` or running matOptimize again.

**Comment by AngieHinrichs** [comment]
@aviczhl2  I believe this is fixed in the 2023-05-10 tree on the main site -- please let me know if you see any more problems, thanks again.

**Comment by AngieHinrichs** [comment]
> with 2 FL.2+C10228T nodes and only one of them identified as FL.2.1.

Thanks @aviczhl2 -- I think this has been fixed now because when I look at the full tree in taxonium I see only one significant C10228T node (green):
<img width="416" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/186983/493e1c53-9ab1-4a1f-ad0e-b2e6bea25e54">
-- there is one stray green sequence in the messy branch just above FL.2.1 (possible artefacts on 28251 and 28254), USA/GA-CDC-QDX48853515/2023|OQ861718.1|2023-04-06.  

If you're still seeing the problem please send a sequence name from each FL.2+C10228T node and I'll look again.  Meanwhile @yceh recommended a different parameter for matOptimize that makes it take more time but should avoid the double-node problem from now on.
