### ISSUE TITLE
FL.1.5.1 with S:A67S 12 seq. in DR, 1 in Canada and 2 in the USA

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#408]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/6fb834d4-2c3b-402c-9964-11dd124cf811)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_37448_af370.json?c=gt-S_67
EPI_ISL_17955834 EPI_ISL_17956224 EPI_ISL_17956247 EPI_ISL_17956225 EPI_ISL_17976076 EPI_ISL_17976093 
First seq: 2023-06-10
Most Recent: 2023-07-01
Query: G21761T, C21036T, G20060T

**Comment by BorisUitham** [comment]
12 seq. Remember 67v was defining for ba.1

**Comment by BorisUitham** [comment]
Theres one in spain now too, think it might be a local case. It has s:554d too which is not as good as s:554k but it is an convergent position

**Comment by BorisUitham** [comment]
@oobb45729 hey, you seem to know this stuff well. Could you help me figure out if this a67s mutation could have much impact on the ntd region?
https://www.sciencedirect.com/science/article/pii/S2001037021004268
"substitution of Ala by Val at position 67 (A67V) is associated with the establishment of novel hydrophobic interactions with Ile 100, Phe 79 and Ala 263 residues"
"Based on our molecular modeling of the spike 3D structure, Ala 67, Asp 80 and Val 143 residues maintain a rigid network of interactions. In this context, A67V, D80Y, D80A and V143F variants are predicted to rewire the network of these interactions, and to either promote the establishment of new hydrophobic interconnections (A67V) or induce a loss of intraloop hydrogen bonds (D80Y, D80A) and interloop hydrophobic interactions (V143F). This might hinder NTD recognition by neutralizing antibodies from convalescent plasma. In this context, recent studies revealed that in frame deletions of NTD amino acid sequence in SARS-CoV-2 strains that affect β3-β4 (Δ69-70), β9-β10 (Δ141-144, Δ146) and β14-β15 loops (Δ243-244) are associated with immune escape in patients"

So this research suggested that ba.1s a67v migve helped with ba.1s immune evasion, however it wasnt present in any dominant omicron afterwards. Perhaps this wasnt needed for ba2 because it got the 69-70 deletion, and of course much of the ba.5 had the 144 deletion. But I dont think a67s has been studied much. A67V replaces a hydrophobic sidechain with another, but serine is in the polar uncharged sidechain. Do you think this could be significant?

**Comment by oobb45729** [comment]
I don't know much about A67V/A67S, but I think that for non-RBD residues, immune escape became important after the middle of 2022. So if a mutation happens more frequently after the middle of 2022, it may be about immune escape, like E554X, which is known to escape some SD2-targeting antibodies. If a mutation happens less frequently after the middle of 2022, it may be no t about immune escape, like T95I and A222V, which are known not to contribute much to immune escape. The patterns of A67V/A67S look more like the latter case than the former case to me.

There is something that might be notable about A67S though. Like ORF9b, There's an alternative ORF inside S protein's coding region called ORF2b with two possible start codons. There's evidence that it is translated but as far as I know, we don't know what ORF2b's functions are. A67S would lose the first possible start codon of ORF2b.
