### ISSUE TITLE
AY.24 Singlet, Indonesia with 37 spike mutations, >113 private mutations

### ISSUE THREAD

**Issue by ryhisner** [sars-cov-2-variants/lineage-proposals#437]
EPI_ISL_17997249
AY.24, Indonesia, Jakarta, Jakarta Utara — 2023-6-7

I'm still analyzing this one, but I wanted to put in in here for the record. I've probably documented and looked at more chronic-infection and long-branch sequences than anyone, and this is the most remarkable I've ever seen. It's particularly striking to see so many spike mutations in a chronic Delta, which almost always have far fewer spike mutations—especially RBD mutations—than chronic-infection sequences from other lineages. 

https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/LEGENDARY__AY.24_Indonesia_2023_6_7___EPI_ISL_17997249.json
<img width="1508" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/836213c3-e4f2-421a-985c-e3c2b754e186">

Here's my preliminary summary of its private mutations. It's full of cryptic/chronic-infection classics.
<img width="1470" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/341d634f-0e5a-4ea3-b2f9-733e0b258281">

**Comment by ryhisner** [comment]
A few speculations on the large number of RBD mutations in this one.

Deltas—even chronic-infection and cryptic Deltas—are notorious for seemingly being unable to pick up many additional spike mutations, particularly RBD mutations. This sequence obviously has plenty. What enabled this? No way of telling for sure, but there seem to be a few fascinating hints.

**• S:N501Y** — N501Y was essential to the most successful VOC before Delta emerged. It seemed likely that some Delta lineage would pick up N501Y, which is known to increase ACE2 affinity, yet none did. It's been rare to see N501Y even in chronic-infection Delta sequences. Why exactly N501Y is incompatible with Delta has never been explained. This Delta managed not only to get N501Y but also Q498R, giving it the magic combo. Why was it able to do so? Perhaps it has something to do with the spike reversions discussed below.

**• Spike Reversions R452L, K478T, and N950D** — These three mutations are universal in Deltas, and all three are reverted in this sequence. This seems unlikely to be a coincidence. BA.4 and BA.5 had L452R, T478K, and N501Y, so these three are obviously not fundamentally incompatible. But what if L452R and T478K are for some reason incompatible with additional RBD mutations unless they are accompanied by Q498R-N501Y? In this context, I think the incompatibility of XBB lineages with L452R is noteworthy, as is the current trend in XBB lineages away from T478K—whether through reversion or substitution. This tendency was also present in BA.2.3.20. 

I have no idea whether the N950D reversion plays a role in any of this. It seems unlikely, but who knows?
<img width="1422" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d73a6897-56ce-4aca-8fab-b13fec853308">



**• S:Q498R-N501Y combo** — This is the only Delta I'm aware of that has ever had Q498R-N501Y. In fact, this combo, despite conferring an enormous increase in ACE2 affinity, is almost unheard of outside of Omicron. There are a few Beta and Gamma singlets with Q498R-N501Y and that's it. It's a mutational combination that's now universal, yet it may have only independently occurred fewer than a dozen times (in documented sequences). Why has this combination, which seems massively beneficial, been so rarely achieved? There were probably hundreds of thousands of documented sequences with N501Y but not Q498R (e.g. virtually all Alpha, Beta, and Gamma sequences), yet virtually NONE ever picked up Q498R, which only requires a simply A->G mutation, which are common. 

This seems a real mystery to me, but it seems to support my hypothesis that there is an ideal level of ACE2 affinity, above which stronger ACE2 binding is deleterious. Q498R-N501Y may provide such a huge increase in ACE2 affinity that it is only viable when simultaneously accompanied by mutations that decrease ACE2 affinity. S:Q493R, found in BA.1, BA.2, and this Delta sequence seems one good candidate for such a role. If adding Q498R to N501Y requires the simultaneous addition of another spike mutation, that would help explain why it has so rarely occurred.

**Comment by ryhisner** [comment]
A few other observations

**• ORF8 Killer** — This Delta has C27889T, the same mutation in BA.5 that spoils the ORF8 TRS and dramatically reduces ORF8 expression. Still more evidence that ORF8 expression is being strongly selected against.
<img width="1049" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f6010e9c-26b9-4425-825e-44417d8b08f1">



**• Cryptic/Chronic Classics** — Cryptic wastewater variants and the most extreme chronic-infection sequences tend to have a lot in common, and this sequence contains most of the classic, distinctive mutations found in cryptics/chronics. These include:
—Spike: K417T, L828F, D1153A
—ORF3a: Q213X
—ORF7a: A82V (reversion in Delta), A105V
—ORF9b: I5X
—ORF1a: V38A, K1795Q, 
—ORF1b: L314P (reversion), F2314X
—s2m mutations: this one has two, T29742G (reversion) and A29756T


**• Omicron Similarities** — As with other extreme chronics & cryptics, this one has a number of mutations also found in BA.1 and/or BA.2, such as:
—Spike: ∆69-70, S477N, Q493R, Q498R, N501Y, H655Y
—ORF1b: R1315C, T2163I

**• Unique double nucleotide mutation at 3631-3632** — This is the only sequence ever to have T3631A-A3632G. Both of these nucleotide mutations are very rare—only 24 sequences have ever had T3631A and just 344 have had A3632G. None have had both. It doesn't form a TRS motif or anything, so it's hard to make sense of. T-->A mutations in general are rare. Maybe it has some hidden purpose, or maybe it's just an extremely unlikely coincidence. 
<img width="290" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/5bfaf275-80b1-4f6b-b493-a99075c10df9">

**Comment by FedeGueli** [comment]
About the rbd reverrsions please keep in mind that Indonesia saw a sustained circulation of B.1.466.2 that went on circulating through early 2022 notwithstamding it has been displaced by Delta. 21sequemces of it has S:H655Y while it had as defining S:681R and S:439K. So if a recombinatiiom happemed it should have bern after 439 until the end of the spike . There have been singlets with M:A2V and orf3a:P104S but i dont think they are related with this.

**Comment by oobb45729** [comment]
S:Y449R is more puzzling to me though, because the Y501-R498 combo seems to rely on Y449 to work. BA.2-related lineages generally don't like Y449X (some BA.1s can have Y449X probably due to G496S).
I think this one likely gained Y501-R498 through recombination with Omicron.

**Comment by oobb45729** [comment]
C22916T suggests that if there's really an R452L, it's likely R452W first, and then W452L.

**Comment by oobb45729** [comment]
Up till now, the only other mutations are fixed in Omicrons and not far from R498-Y501 are Y505H and N440K. It does not make sense to me that R498-Y501 would need Q493R.

**Comment by oobb45729** [comment]
ORF1a:A1306S is in 21J but not in AY.24. BA.2 has ORF1:G1307S. It is probably not a coincidence.
ORF1a:D2980X are also chronic classics.
ORF1a:A3143V is in EG.5.

**Comment by ryhisner** [comment]
@oobb45729, the worst chronic Delta before this one—an AY.103 from Houston, Texas—also had the 2-nuc S:Y449R. That one had Q498Y-N501T instead of Q498R-N501Y, but these are the two of the three sequences ever to have had Y449R. (The other was a C.1.2 from South Africa.)

**Comment by c19850727** [comment]
Also S:L828F (as well as ORF1b:F2314x mentioned by @ryhisner already) is common in wastewater samples but pretty rare in sequences of nsopharyngeal and oropharyngeal swabs.

**Comment by Sinickle** [comment]
There are 3800 Alpha sequences that have additional mutation S:583D, in addition to defining mutation S:570D. Maybe similar to S:571G, S:583D in this Delta. 

@oobb45729 previously stated 455W works well with 493R.  
The K417T 452L 493R combo is also something that came up advantageously often prior to Omicron dropping Q493R. K417T seemed to stop being advantageous after Q493 reverted.

**Comment by BorisUitham** [comment]
@Sinickle yes thanks for mentioning; heres a quick link to the discussion: https://github.com/sars-cov-2-variants/lineage-proposals/issues/95#issuecomment-1603735331

**Comment by silcn** [comment]
Haven't seen anyone mention yet that S:E340D looks like a sotrovimab escape mutation - haven't seen those in a while!
Does anyone know if/when sotrovimab was used in Indonesia? I can't seem to find any info online. It certainly looks like it wasn't used during the BA.1 wave, as that's when S:340 mutations were most common but there is only one BA.1 sequence from Indonesia with a mutation at S:340.

**Comment by FedeGueli** [comment]
> Haven't seen anyone mention yet that S:E340D looks like a sotrovimab escape mutation - haven't seen those in a while! Does anyone know if/when sotrovimab was used in Indonesia? I can't seem to find any info online. It certainly looks like it wasn't used during the BA.1 wave, as that's when S:340 mutations were most common but there is only one BA.1 sequence from Indonesia with a mutation at S:340.

Anyone has the nmes of submitters? i got in touch in the oast with some scientists of the indonesian diaspora i could ask them if needed.

**Comment by MaxPower2023** [comment]
This sequence has now been removed from GISAID. Does anyone have information why? PS: Many thanks for all the discussion and shared knowledge - really amazing community!

**Comment by c19850727** [comment]
@silcn in addition to S:E340D, S:K444E and F456L (and maybe some other mutations?) are also associated with resistence to various mABs. 

But I guess this patient were not somehow treated with multiple mABs though?

**Comment by aviczhl2** [comment]
Indonesia only submits 32 seqs after 2023.6.1.

 If this one is randomly sampled it probably means it has already infected millions.

**Comment by silcn** [comment]
> If this one is randomly sampled it probably means it has already infected millions.

If this had infected millions we would almost certainly know by now, either because of hospital pressure or a sequence showing up somewhere else. No sign of it in travellers from Indonesia arriving in Singapore, collection date up to 12 July.

This doesn't mean it couldn't have been randomly sampled. It could be spreading at low levels, or this could be a chronic infection that got picked up by chance. More likely that it's a hospitalised patient IMO.

**Comment by aviczhl2** [comment]
> If this had infected millions we would almost certainly know by now, either because of hospital pressure or a sequence showing up somewhere else. 

Nope. Millions of infections actually won't affect the infection baseline very much, maybe 3-5%, which won't cause much additional hospital pressures, so not in medias.

Also, if you search BF.7.14/BA.5.2.48 you'll find ~2000 seqs outside China, and these 2 variants infected >1 billion Chinese people,  which means ~5 million infection=1 foreign seq.  One million is small enough not to appear elsewhere.

**Comment by silcn** [comment]
> Nope. Millions of infections actually won't affect the infection baseline very much, maybe 3-5%, which won't cause much additional hospital pressures, so not in medias.

Depends what we mean by "millions". Indonesia has a population of about 280 million. In most of the world, people are getting infected very roughly once per year [ignore the scaremongerers/grifters claiming 3 per year is the average], so that's ~23 million infections per month. 5 million extra infections in a month would be a >20% increase. If there have been millions of second-generation AY.24 infections, here are your options:

1. This lineage only has a small growth advantage, so must have been around for many months in order to accumulate millions of infections. Despite this, it has only been detected once and never outside Indonesia (see below for why this is unlikely).
2. The growth advantage is big. In this case you'd expect signs of increased hospitalisations around where the variant originated, and probably detections from travellers to Singapore by now.

> Also, if you search BF.7.14/BA.5.2.48 you'll find ~2000 seqs outside China, and these 2 variants infected >1 billion Chinese people, which means ~0.5 million infection=1 foreign seq. Currently the global seq capacity is much smaller than 2022.12-2023.1, which means maybe ~2 million infection=1 foreign seq. One million is small enough not to appear elsewhere.

The winter 2022/23 China wave is not a fair comparison for multiple reasons. Because of the lack of immunity from prior infections, BF.7.14/BA.5.2.48 were able to circulate widely there at a time when they were at a strong disadvantage anywhere else in the world. Thus there were far fewer infections outside China, hence far fewer foreign sequences. In addition, international travel from China was still reduced due to quarantine rules imposed by China (until some time in January) and by other countries on Chinese travellers during the wave.

XBB.1.9.1 is a fairer comparison as it may have originated in Indonesia, and in that case there were foreign sequences from very early on. The first three sequences were from Malaysia, Indonesia and Singapore.

**Comment by BorisUitham** [comment]
I would just apply occams razor and assume this is just the one patient unless a second sequence gets uploaded that is clearly not the same individual

**Comment by aviczhl2** [comment]
> XBB.1.9.1 is a fairer comparison as it may have originated in Indonesia, and in that case there were foreign sequences from very early on. The first three sequences were from Malaysia, Indonesia and Singapore.

 XBB.1.9.1(and actually almost every lineage) may not come from Indonesia, but from undersampled regions like Afghanistan or North-eastern provinces of India, or anywhere as >80% of the SE Asian provinces actually don't upload seqs. 

I list BA.5.2.48/BF.7.14 as these two may be the only ones that have clear origins.

**Comment by FedeGueli** [comment]
Keep in mind Indonesia had sequencing very skewed toward hospitalized patients, this has been comfirmed me by aithors of one of the few papers on Indonesia epi evolution back in 2022. Things cpuld have changed since but i suspect this as the other BA.2.3 spotted by @krosa1910 could come from that kind of sampling strategy

**Comment by ryhisner** [comment]
> This sequence has now been removed from GISAID. Does anyone have information why? PS: Many thanks for all the discussion and shared knowledge - really amazing community!

I have no idea why. If someone finds a way to contact the submitters, we might find out, but messages to the submitters (not by me but others) have so far not gotten any response.

The exact same thing happened to a similar sequence from England not long ago, so this is not the first time a sequence of interest has disappeared from GISAID without explanation.

**Comment by silcn** [comment]
I can think of a few possible reasons why the sequence could have been removed. Some much more likely than others.

- The patient did not want their sequence to be publicly available.
- The hospital treating the patient did not want the sequence to be publicly available, in order to protect the patient's privacy.
- There is a paper in preparation on this case and the sequence is being withheld until it is finished.
- The submitters were annoyed at how many emails they were receiving through GISAID and removed the sequence.
- The submitters wrongly assumed the sequence was contamination or an artefact and removed it.
- The lineage has spread, and Indonesian authorities are trying to cover up the fact that Delta is circulating in their country as they are worried about travel bans being imposed on them.
- The lineage hasn't spread, but the submitters and/or health authorities don't want the sequence being used as "evidence" that Delta is circulating.

**Comment by FedeGueli** [comment]
Closing this for now luckily.
