### ISSUE TITLE
XBB.1.16.6 (S:F456L) with S:L455F emerging in Florida (14 seqs)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#531]
I was monitoring a sublineage of XBB.1.16.6 since it was one sequences that gained convergently S:L455F, as today it reached 4 sequences so it is better to track it here:

Defining mutations:
XBB.1.16.6 >> C8947T > A10861G > T23986C > **S:L455F** (G22927T)

Gisaid query:G22927T, A10861G,T12730A,-C27937T

Samples: 4 (Florida 2, New Jersey 1 with travel history, Washington 1 )

EPI_ISL_17971832, EPI_ISL_18037649, EPI_ISL_18060741

Tree:
![Schermata 2023-08-03 alle 14 34 53](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/7faf1c77-2f48-404d-93da-22c926582e28)
![Schermata 2023-08-03 alle 14 38 33](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0fef43d5-7708-4311-bd3d-980348aa14c0)
(Note that already S:L455F has popped up in XBB.1.16.6 )
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_ad1e_b9e410.json?c=gt-S_455&label=id:node_6715319

**Comment by ryhisner** [comment]
I noticed that two of the three sequences from Florida have A13912T + A13913C. I figured adjacent A->T and A->C mutations had to be TRS-related, and they are. It's a bit strange because most of the matching nucs here are in the 5' extended homology region rather than the core TRS. 

Normal view on top, annotated version on bottom. 
<img width="1445" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/0c6d0384-9152-40c3-8bdb-09f081e262ce">



I looked to see if any other sequences with A13912T + A13913C had additional nucleotide mutations that would make an ever better match for the TRS-L, and it turns out there have been 19 sequences with T13906C, A13907T, & T13908G. Those form ORF1b:Y147L (NSP12_Y156L)

Again, unannotated view on top, annotated version on bottom.
<img width="1478" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/e4fb5a17-5694-46d9-899c-cc218fe68be2">

**Comment by FedeGueli** [comment]
two more sequences from Sweden

**Comment by FedeGueli** [comment]
LAST FROM UK.

**Comment by FedeGueli** [comment]
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_38fc8_f79060.json?label=id:node_6855109

![Schermata 2023-08-18 alle 16 01 15](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d3dbcae7-c997-43e5-bc76-72bbe85ba87e)

**Comment by FedeGueli** [comment]
Thank you i am proposing it. it will the first FLip +478 to reaching "designation standards"

**Comment by FedeGueli** [comment]
Designated JF.1 via https://github.com/cov-lineages/pango-designation/commit/7e6a6613234930ff49365e7984615e9ad93e1b63
