### ISSUE TITLE
XBB.2.3 with ORF1b:R2613H>N, ORF1b:P2612L, then saltation with ORF1a:H1113N, S:G75V, S:G184V, S:N658K, ORF3a:T89I and ORF7a:E95Q (27 seqs, mainly in Sweden, 3 countries)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#539]
**Defining Mutations:** `XBB.2.3` > `G21305A(ORF1b:R2613H/nsp16_R216H)` > `C21304A(ORF1b:R2613N/nsp16_R216N)` > `C21302T(ORF1b:P2612L/nsp16_P215L)` > `C3602A(ORF1a:H1113N/nsp3_H295N), T9208A, C10702T, C11950T, A15027T, T21180C, G21786T(S:G75V), G22113T(S:G184V), C23536A(S:N658K), C25658T(ORF3a:T89I), G27676C(ORF7a:E95Q)`
**Query:** `G6536A, G21786T, C23536A`
**Earliest seq:** 2023-05-14 (`EPI_ISL_17822604`, Victoria, Australia)
**Latest seq:** 2023-07-22 (`EPI_ISL_18053336`, Stockholm, Sweden)
**Sampled Countries:** Sweden (14), Australia (1)

**Saltation Profile:**
mutations on nearest neighboring branch
```
nuc	unique	C3602A, T9208A, T21180C, C23536A, G27676C
nuc	homoplasies	C10702T, C11950T, A15027T, G21786T, G22113T, C25658T
ORF1ab	unique	H1113N
S	unique	N658K
S	homoplasies	G75V, G184V
ORF3a	homoplasies	T89I
ORF7a	unique	E95Q
```
![mut](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/089ea22e-01e4-43c4-996a-a48d51e05014)

<details><summary>Genomes: </summary>

`EPI_ISL_17822604, EPI_ISL_17850045, EPI_ISL_17956050, EPI_ISL_17956075, EPI_ISL_17956081, EPI_ISL_17976152, EPI_ISL_17976170, EPI_ISL_17990657, EPI_ISL_17990666, EPI_ISL_17990689, EPI_ISL_18009593, EPI_ISL_18041940, EPI_ISL_18053306, EPI_ISL_18053336-18053337`

</details>

**UShER:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_247e6_caf4d0.json?f_userOrOld=uploaded%20sample&label=id:node_7181426
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/695e32d5-c388-408b-b25d-e43f2f61fe76)

**Comment by FedeGueli** [comment]
Gret spot @NkRMnZr this worries me not for the saltation itself but for the pattern shwon before the saltation, i ask @ryhisner @thomaspeacock to review it , i suspect there could be some TRS thing involved in that double/triple mutation at the end of Orf1b

**Comment by FedeGueli** [comment]
I am referring to this:
![Schermata 2023-08-04 alle 10 59 28](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/b7f3e0ce-9c3c-40e3-935d-65aa4d6f7ec6)

**Comment by ryhisner** [comment]
Yes, the C21302T, C21304A, G21305A combination has repeatedly evolved probably hundreds of times. It is a novel TRS motif that was also discussed by Theo Sanderson, Tom Peacock, and David Bauer in the paper below. https://www.biorxiv.org/content/10.1101/2022.04.20.488895v1.full  

Sometimes only one of those three mutations (either C21304A or G21305A) will be present and other times C21304A & G21305A are there but not C21302T. Here's a diagram I made showing that these mutations create a perfect match for the TRS-L, with C21302T creating extended homology on the 5' side. 
<img width="1423" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/1e5fc259-1bf8-4832-be07-92e51135c74c">
. 


.
This combination has sometimes evolved all in one jump—as is the case for this lineage—but also stepwise, one mutation at a time, as seen in the BA.2.12.1 and BA.5.1 trees below.

.
<img width="1502" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/a0e95abd-8221-4a9e-a22b-d63f418ab473">
.

I know of two possible explanations for the repeated emergence of this mutational pattern
**1)** It's a way to reduce the production of full-length genomes (which would increase the proportion of subgenomic RNAs produced)
**2)** It creates a new peptide/protein that serves some function.

I favor the second hypothesis, mainly because of the abundance of start codons immediately after the new TRS. Three of them are in frame with each other but out of frame with respect to the normal reading frame. If translation starts at the first start codon, it would create a 27-AA protein as the next stop codon in that frame doesn't come until 21398-21400. 

<img width="1491" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/26865ec3-19ed-44d3-8ff2-cd2861a25f7a">

**Comment by FedeGueli** [comment]
Thank you @ryhisner

**Comment by FedeGueli** [comment]
@ryhisner have we seen it as defining in big/designated  lineages yet?

**Comment by FedeGueli** [comment]
Jump to 24. all swedish ones.

**Comment by FedeGueli** [comment]
no sign of sustained growth closing it for now.
