### ISSUE TITLE
fl.1.5.1 with ORF3a:T24I and ORF1a:K120N (101 seq) in USA

### ISSUE THREAD

**Issue by Fearuncle** [sars-cov-2-variants/lineage-proposals#558]
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/4888e7b5-9f05-469c-9d04-5ed871fcdd4c)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/78371872/95a693b5-bff9-4aea-b1a2-1a7cf1ca6138)
tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_3f2c7_e85c00.json?c=gt-ORF3a_24&label=id:node_6786218
gisaid query: T1177C, C25463T, T23031C
first seq: 2023-07-03
Most recent: 2023-07-13
OR287224.1 OR364350.1 OR351345.1 OR346436.1 OR346470.1

**Comment by FedeGueli** [comment]
It seems to have some advantage over parental sublineage: https://cov-spectrum.org/explore/United%20States/AllSamples/Past3M/variants?nextcladePangoLineage=FL.1.5.1*&nucMutations1=T1177C%2CC25463T%2CT23031C&analysisMode=CompareToBaseline& pleaase ping me if it gains further key mutations. otherwise lets look how many times it takes to reach 100.
