### ISSUE TITLE
XBB.2.3 + S:S494P +Orf8:I58T likely emerged in Philippines  (59 sequences) plus sibling lineage defined by silent S:R498R (14 seqs- see what this means in the great comment by Ryan Hisner) 

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#58]
Despite never being sampled in Philippines this sublineage of XBB.2.3 likely emerged there casue two samples from travellers from philippines were sampled by South Korea and Singapore.

Here i want to highlight this sublineage that stems out of XBB.2.3 politomy with S:S494P and then Orf8:I58T , the lineage without counting Orf8:I58T too is wider and it is defined by the  silent nuc mutation :C23054A and counts 12 sequences with the query (T23042C,C23054A) if this will go through the designation process i suggest to designate the entire lineage.

Tree:
![Schermata 2023-05-14 alle 23 46 18](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2f5914f2-ed4f-453c-840b-30ed7dc2735a)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice7_genome_376d1_eeb60.json?c=userOrOld&label=id:node_6985037

Defining mutations:
XBB.2.3>>> G29706T > C4234T > ORF1a:G2091S (G6536A) > S:S494P ( T23042C) > TOrf8:I58T (28066C )

Gisaid query :T23042C,T28066C finds 34

**Comment by FedeGueli** [comment]
@ryhisner please recall to add your analysis here

**Comment by FedeGueli** [comment]
38 as today

**Comment by ryhisner** [comment]
Thanks for the reminder, Fede! I noticed that one branch of this lineage has a synonymous nucleotide mutation in S:498 (C23045A), as pictured below. 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/ecb57990-e00f-4e7a-8b4c-9351c848e337)

While this doesn't change the amino acid there, it does open the door to other S:498 mutations that were previously two nucleotide mutations away. Furthermore, R498K becomes easier to reach, requiring only a relatively common G->A mutation instead of the less common C->A. The path to R498G also becomes much easier, requiring a relatively common A->G mutation rather than a C->G, which is the rarest of all nucleotide mutations.
<img width="1227" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/80155288-5840-4d92-b84f-146e61268221">

**Comment by FedeGueli** [comment]
Thx vm Ryan i added that in the title to find this easily

**Comment by FedeGueli** [comment]
48 and 13 total 61 for this branch as today , growing fast . I will propose once it reaches 100 seq total.

@ryhisner Would you love to propose it once it reached the threshold??

**Comment by ryhisner** [comment]
You can go ahead and propose it, Fede. Once you've done that, I'll just re-add my comment on the synonymous 498 mutation.

**Comment by FedeGueli** [comment]
Guangdong and Philippiines (in Singapore)  the two new seqs. I will propose it. @ryhisner

**Comment by FedeGueli** [comment]
One more seqs for the R498R branch but from Tamil Nadu.
while the main branch is now 59 seqs.

I forgot to propose it but it is worth likely a designation.

**Comment by FedeGueli** [comment]
Now proposed in https://github.com/cov-lineages/pango-designation/issues/2029
