### ISSUE TITLE
FY.3 saltation branch with S:M177I (6 seqs in Tasmania, Australia)

### ISSUE THREAD

**Issue by HynnSpylor** [sars-cov-2-variants/lineage-proposals#612]
Defining mutations:
FY.3>C23191T>T10810C>C27884T>T3541C, C4832T, T8971C, C14931T, G22093A (S:M177I), C25521T, C26029A (ORF3a:Q213K)

Then Branch A (3 seqs) with 15 nuc mutations>5 ORF1ab aa mutations, 1 ORF3a mutation and ORF6a mutation:
<img width="553" alt="屏幕截图 2023-08-15 170513" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/03580036-17e7-4a20-9b11-ade4632228e7">

Branch B (2 seqs)  with 14 nuc mutations>7 ORF1ab aa mutations, S:C1248Y, 1 ORF3a and 1 ORF7b mutation:
<img width="560" alt="屏幕截图 2023-08-15 170820" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/2c7cbed8-b628-487b-8667-677bebdde44e">

GISAID query: T3541C, T8971C, G22093A, A22161G
Earliest seq: 2023-07-13 (Australia- EPI_ISL_18100403)
Most recent seq: 2023-07-30 (Australia- EPI_ISL_18100418)
Countries detected: Australia (5)
Usher Tree:
<img width="907" alt="屏幕截图 2023-08-15 171116" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/121703496/ba2ab3a8-5469-4d0f-bcf2-d3f037fd07ad">
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_9f14_b2c8c0.json?c=gt-S_177&label=id:node_10736300

I suppose 2 branches are corresponding to 2 infection chains. 

Genomes:
EPI_ISL_18100403-18100404, EPI_ISL_18100416-18100418

**Comment by ryhisner** [comment]
These are definite molnupiravir lineages. I the the analysis for both last night, pictured below at the bottom of this post. The nucleotide context statistics are based on the contexts found in previous molnupiravir lineages and are calculated using a tool created by @theosanderson. These calculations are completely independent of the mutation types, so they are an entirely independent line of evidence for MOV sequences.

There was an additional XBL.1 MOV sequence from Tasmania uploaded yesterday, but I won't clutter the page by posting the stats here unless a second sequence shows up.

I'm guessing these two parallel-branch MOV sequences are related to a nursing home outbreak in which MOV was widely distributed. Australia pre-stocked their nursing homes with MOV and use it far more than any other country. The very first MOV lineage that was known to transmit, a BM.2 lineage submitted by @Sinickle in issue #1286 (link below), had two long, parallel MOV branches independent of the primary one. It seems likely that during a nursing home outbreak, MOV as widely distributed and at least two individuals treated with MOV ailed to clear the virus and went on to transmit to others. You can see these parallel MOV branches in the tree pictured below. 
https://github.com/cov-lineages/pango-designation/issues/1286 
<img width="1345" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/124977d6-b2fa-45d3-9197-77a9eff5bcff">
.


Below is my analysis of the two Tasmanian branches. Haven't checked them super close due to lack of time, so let me know if there are mistakes and I'll correct them.


.
<img width="1221" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/fd942c54-6b85-4f7e-a896-90de74949ad1">

<img width="1251" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/2ea56ea4-d9dc-47d9-acc0-7e5a2f2f412f">

**Comment by ryhisner** [comment]
One additional sequence from the top branch today. The collection date is August 1, more than two weeks after the first three sequences on that branch were collected. If the original sequences (all collected between August 13 and Aug 19), represented a nursing home outbreak, it's possible this more recent one could indicate transmission in the wider community. All speculation at this point though. There is no metadata for any of these sequences, unfortunately. Perhaps someone should try to reach out to the Tasmanian lab that sequenced these.

**Comment by FedeGueli** [comment]
Thx Ryan i have added a public label to keep it monitored

**Comment by FedeGueli** [comment]
closing it for now
