### ISSUE TITLE
XBB.1.41.1 (S:335S,403K,478R) sublineage with Orf1a:P1220L and N:H300Y growing internationally (251, > 7% in Louisaina in September)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#629]
Thanks to a question from Marc Johnson if there wer some sublineage with N2 gene test failure  i found this one, maybe it is not related with the question but for sure it is expanding in US and Uk during last month.

Defining mutations:
XBB.1.41.1(S:335S,403K,478R) >> C364T > **Orf1a:P1220L** (C3924T = NSP3_P402L), C18555T > **N:H300Y** (C29171T)

Gisaid query: ,C3924T,C18555T,C364T

Samples 35 From Usa(Alabama) , UK , Ireland, Israel , Australia

<Details>
<Summary>
IDs
</Summary>
EPI_ISL_17974948, EPI_ISL_17989726, EPI_ISL_18012574,
EPI_ISL_18036936, EPI_ISL_18053693, EPI_ISL_18053723,
EPI_ISL_18053726-18053727, EPI_ISL_18053733, EPI_ISL_18053740,
EPI_ISL_18053746, EPI_ISL_18053756, EPI_ISL_18053758,
EPI_ISL_18053760, EPI_ISL_18056768, EPI_ISL_18057661,
EPI_ISL_18060387, EPI_ISL_18060397, EPI_ISL_18065807,
EPI_ISL_18072072-18072073, EPI_ISL_18072081, EPI_ISL_18072093,
EPI_ISL_18092135, EPI_ISL_18095045, EPI_ISL_18097938,
EPI_ISL_18097940, EPI_ISL_18097942, EPI_ISL_18097944,
EPI_ISL_18097953, EPI_ISL_18097964, EPI_ISL_18099263,
EPI_ISL_18104449, EPI_ISL_18107756, EPI_ISL_18108106,
</Details>
First: 
hCoV-19/England/CLIMB-CM7YGDNA/2023 | Original | EPI_ISL_17974948 | 2023-06-25
Last:
hCoV-19/USA/NY-NYULH-15770/2023 | Original | EPI_ISL_18095045 | 2023-08-06

Tree:
![Schermata 2023-08-17 alle 16 31 00](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/2b6d2720-54c2-4f82-911d-4dca12d3c716)
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_35258_e2a400.json?c=gt-N_300&label=id:node_7003861

**Comment by FedeGueli** [comment]
This is flying in Louisiana ( 10% there both in last two weeks of July and the first two of August)
 ping @corneliusroemer consider that N:300 could have an impact on N gene testing.

**Comment by FedeGueli** [comment]
@corneliusroemer i was looking at epi in Louisiana it seems quite fstly growing with this lineage at 101% but XBB.1.41 there with XBB.1.41.2 too is around 17-18% in August (over 100 samples) while S:F456L seems still far at less than 7-8% https://twitter.com/BNOFeed/status/1694484633365189061
also hospitalization are announced to be on the rise by CDC (Texas,Georgia, Tennessee too) :  https://twitter.com/Laurie_Garrett/status/1694372598073676219

I suggest to designate this one too also for the possible N-GTF due to N:300 mutated.

**Comment by FedeGueli** [comment]
new samples Wi, NY

**Comment by FedeGueli** [comment]
67 tot. Many international samples beyond US.

**Comment by FedeGueli** [comment]
68 prevalence in Louisiana seems less than before but anyway around 10%

**Comment by aviczhl2** [comment]
Designated JW.1

**Comment by Over-There-Is** [comment]
> Designated JW.1

JC.5

**Comment by FedeGueli** [comment]
Desingated JC.5 via https://github.com/cov-lineages/pango-designation/commit/d3d7c0998d613c9a35c5746cd03bb6476c492f40

**Comment by ryhisner** [comment]
Fede, this lineage has a large deletion in ORF7a. Most sequences just appear to lack coverage there, but a few seem to register the deletion correctly—∆27523-27695. It causes a frameshift that completely changes the last 20 AA of ORF7a and which also leads to fusion with ORF7b. Furthermore, most of the recent sequences from England also have the new ORF7b—∆27791-27792. 

So this results in a brand new protein with the first 44 AA from ORF7a, the next 20 from a new reading frame in ORF7a, and the last 32 from the new ORF7b, the last 17 residues of which are totally different from normal ORF7b. 

On top of all that, all the sequences with the new ORF7b also have a 23-nt deletion that erases the ORF8 TRS (∆27887-27909). Damn.

<img width="1364" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/f9bff8bf-b82e-4df3-aefc-57b5c7c074a9">

I may have made a mistake somewhere, but I believe the new AA sequence for this modified ORF7a-ORF7b protein would be this: 
<img width="1437" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/9dd71d4f-3aaa-4c3c-9bfb-3f9e850fb476">

Residues 45-64 are the brand new ones resulting from the new reference frame at the end of ORF7a. Residues 65-77 are the normal first 13 in ORF7b, and 78-95 are the new ORF7b residues that result from the frameshift caused by ∆27791-27792.

**Comment by FedeGueli** [comment]
Thank you @ryhisner ! great spot! i noticed that JC.5.1 did a noticeable comeback in collection 42 just yesterday evening, i left this tab open on my opc when felling asleep and this morning i found your comment! This is something to watch closely, in my view. Do you think all the JC.5.1 sequences have the Orf7a deletion? but likely not everyone has the new orf7b right?
I ve identified a possible subbranch with the query: C9565T, C11758T, C12325T  that similarly fast as Jn.1 baseline: https://cov-spectrum.org/explore/World/AllSamples/Past2M/variants?nextcladePangoLineage=JN.1*&nucMutations1=C9565T%2CC11758T%2CC12325T&analysisMode=CompareToBaseline& obviously it could be biased by N factors so to take it with a big grain of salt.

**Comment by FedeGueli** [comment]
@ryhisner  i have just opened a dedicated issue from your comment: #1328
