### ISSUE TITLE
BA.4.6 saltation with ORF1a:K120N, ORF1a:V86F, S:L455F (5 seqs, Switzerland), further step saltation gained S:F456L, S:E484V, S:V486F_reversion (3 seqs)

### ISSUE THREAD

**Issue by NkRMnZr** [sars-cov-2-variants/lineage-proposals#703]
**Defining Mutations:** `BA.4.6` > `T23449C` > `A13809C` > `G625T(ORF1a:K120N)` > `G521T(ORF1a:V86F), ins688_CAT(ORF1a:ins_141H), G22927T(S:L455F)`
**Query:** `G521T, G22927T,A13809C`
**Earliest seq:** `2022-09-14` (EPI_ISL_15118346)
**Latest seq:** `2023-08-08` (EPI_ISL_18129944)
**Sampled Countries:** Switzerland

<details><summary>Genomes: </summary>

`EPI_ISL_15118346, EPI_ISL_16669313, EPI_ISL_17475799, EPI_ISL_17831941, EPI_ISL_18129944`
</details>

**UShER:**
https://nextstrain.org/fetch/raw.githubusercontent.com/NkRMnZr/hSC2-Tracking-Log/main/JSON/EPI_ISL_18129944%20BA.4.6%2BL455F%2BF456L_Cluster_Switzerland.json?label=id%3Anode_8183846

view from `BA.4.6` polytomy
![poly](https://github.com/NkRMnZr/hSC2-Tracking-Log/assets/125747944/242c9eb9-4789-4d71-baef-9ca622ec49e2)

`T23449C` branch diversity
![step](https://github.com/NkRMnZr/hSC2-Tracking-Log/assets/125747944/bbc1a429-f07a-4cf8-974c-3f3f549c65fe)

details
![details](https://github.com/sars-cov-2-variants/lineage-proposals/assets/125747944/e237359a-b502-47d9-90d3-b4f2a24115d3)

**Trivia:**

- Probably single chronic. 
- Most interesting part is, unlike most other lineages that gained '_flip combo_', it gained `S:L455F` first rather than `S:F456L`, on a `BA.4` backbone with ACE2-binding affinity sacrificial `S:F486V`, don't know how much binding affinity is left there, but it _can still_ later gain `S:F456L` and a reversion of `S:V486F`, which will largely improve it.

**Comment by aviczhl2** [comment]
Is it a single chronic patient?

**Comment by FedeGueli** [comment]
The shape of the tree makes me think it is a chronic infection, but having the FLip it has to be monitored closely:
![Schermata 2023-08-27 alle 17 06 10](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/4167e07a-571c-4738-b741-b7133cd9a089)
This is the picture of the last sample. @thomaspeacock do you think S:P681Y could still permit the furin cleavage? sequence: SYQTQTKSYRRARSVASQ

**Comment by silcn** [comment]
@thomasppeacock tagging the correct username

**Comment by thomasppeacock** [comment]
I think it would be less efficient - maybe even inhibited due to the bulky amino acid? might fit with it being a chronic?

**Comment by ryhisner** [comment]
I feel pretty certain these are from a single individual, both because of the shape of the Usher tree and because of the time distribution of the collection dates, which suggest a patient with a known chronic infection being sampled every few months. Below is an annotated Nextclade view of the ~400-520 residues of spike. 

<img width="1113" alt="image" src="https://github.com/sars-cov-2-variants/lineage-proposals/assets/33738461/d886342c-df6c-4feb-8854-a4852a5774b0">


There are a couple interesting things worth noting. First, unlike the FLip variants currently growing (and which, IMO, will become dominant if BA.2.86 doesn't steamroll them all), this one got L455F first, then F456L. We've seen L455F without F456L previously, so it's not surprising to learn that FLip can be acquired through both routes. 

Second, this BA.4.6 traced two patterns that have become extremely common in recent BA.4/5 chronic-infection sequences: reversions at 484 and 486. In this particular case, after the A484E reversion, it moved on to E484V. It's common for chronic-infection variants to trace out patterns that are later repeated in circulating variants. Does the current incipient 484K comeback indicate the beginning, at a population level, of the same sort of unfavorable environment for E484A that we've seen in chronically infected individuals?

**Comment by FedeGueli** [comment]
> @thomasppeacock tagging the correct username

really is that?  tagged him wrongly hundred of times.

**Comment by FedeGueli** [comment]
> I think it would be less efficient - maybe even inhibited due to the bulky amino acid? might fit with it being a chronic?

Thx Tom

**Comment by thomasppeacock** [comment]
> > @thomasppeacock tagging the correct username
> 
> really is that? tagged him wrongly hundred of times.

Afraid so! feel free to re-tag me in if theres any ongoing stuff thats relevent - finding it hard to keep on top of the github stuff these days!

**Comment by FedeGueli** [comment]
> > > @thomasppeacock tagging the correct username
> > 
> > 
> > really is that? tagged him wrongly hundred of times.
> 
> Afraid so! feel free to re-tag me in if theres any ongoing stuff thats relevent - finding it hard to keep on top of the github stuff these days!

Thx really i think sometimes i got it right copying&pasting from some issue u commented but then i went by memory and i missed the P insertion ;)

**Comment by FedeGueli** [comment]
No new sequence.
