### ISSUE TITLE
XBB.1.9.1 with S:Y200C and S:T478R, Orf1b:H641Q (NSP12_H650Q) in the branch with Orf1a:T2007I (NSp3_T1189I) and N:T166I (9 sequences)

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#73]
**This was first spotted by @JosetteSchoenma and independently re discovered and proposed, please Josette add here your comments!**

Transferred here from https://github.com/cov-lineages/pango-designation/issues/2002
Noticed this small XBB.1.9.1 sublineage with convergent mutation S:Y200C with XBB.1.22.1

Gisaid query: A22161G,C15390A, T26457C, G12907A

Tree:
![Schermata 2023-05-19 alle 19 50 50](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/de2631b3-4676-40ad-bd48-e35e7069ab32)
![Schermata 2023-05-19 alle 19 51 09](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/17368df3-63bd-47b2-9628-54f01c32ff74)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice36_genome_1a836_7b0170.json?c=gt-S_200,478&label=id:node_6863601

Defining mutations:
XBB.1.9.1 >> > Orf1a:T2007I (C6285T) > N:T166I (C28770T) > G12907A, A27507C >S:Y200C (A22161G )> Orf1a:G519S (G1820A), Orf1b:H641Q (C15390A), S:K478R (C>A22995G), T26457C >

Sequences:
EPI_ISL_17408992-17408993, EPI_ISL_17614765, EPI_ISL_17614857,
EPI_ISL_17657166, EPI_ISL_17661231, EPI_ISL_17680081,
EPI_ISL_17682885, EPI_ISL_17683629

Countries:
Interesting one of the samples intercepted by US airport surveillance comes from a traveller from Singapore
![Schermata 2023-05-19 alle 19 51 37](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/d04efe42-f512-43db-bb3f-66ee19ec9346)

**Comment by JosetteSchoenma** [comment]
Thanks, @FedeGueli . 
Yes, I was studying this one yesterday. I actually think it might be a XBB.1.9.1/XBB.1.9.2 recombinant. Nextclade calls them EG.2 (XBB.1.9.2.2), because of S:K478R and A27507C and then says XBB.1.9.2 mutation A16878T has been reverted. But the combination of C6285T, C11956T and C12789T really makes, the first part at least, XBB.1.9.1. So, that would make it XBB.1.9.1 at least until 16878 and XBB.1.9.2 at least from A27507. 

Another option would be that XBB.1.9.1 recombined with EG.2, which already has A22995G (S:K478R). The early English sample QEUH-32704479 from 2023-3-10 makes that less likely though. Since that also has the uncommon ORF3a frameshift plus S:Y200C, but not S:K478R.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/7673acf8-e3ac-430c-bb82-d3009a75be42)

If the Usher tree is correct, A27507C has been gained (by recombination?) before the beforementioned frameshift and the gain of S:K478R, and has not only resulted in the this issue's sublineage, but besides the English sample mentioned also in the Indonesian EPI_ISL_17551409, plus 36 mainly South Korean samples with an extra A28113G.

If that is the case, maybe it is best if either an XC? or an XBB.1.9.1 sublineage is designated before 2 sublineages of it get designated.

A broad query would be C6285T, C11956T, A27507C, to which S:K478R or A28113G could be added to find the various sublineages.

There are 2 new ones, by the way, EPI_ISL_17682885 from Tasmania and EPI_ISL_17689132 from the Netherlands.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/bab81a17-67a1-4603-a9cc-aee0b7a4dbe8)

**Comment by FedeGueli** [comment]
ThAnk  you @JosetteSchoenma ! please propose this one in the main page i think it deserves a fast review by Pango.

**Comment by FedeGueli** [comment]
And dont you think that XBB.1.22.1 with S:Y200C could be involved? XBB.1.22 is basically XBB.1.9 without the double orf1a mutation.

**Comment by JosetteSchoenma** [comment]
@FedeGueli I did investigate that. It is not impossible, but XBB.1.22.1 does not have A27507C, which is seen in both branches. If it recombined with XBB.1.22.1 it must be a separate recombination from the South-Korean branch and the Indonesian sample, while recombination with XBB.1.9.2 could explain all samples.
