### ISSUE TITLE
Potential EG.5.1  sublineage with S:A344T S:R403K emerged in Germany Contamination likely.  Help wanted

### ISSUE THREAD

**Issue by FedeGueli** [sars-cov-2-variants/lineage-proposals#759]
@angiehinrichs could you take a look at this please?

tree 1:
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice4_genome_test_1dedd_8b2920.json?c=gt-nuc_9693&gmax=10693&gmin=8693&label=id:node_6954089

tree 2 (wastewater): 
https://nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_1dedd_8b2920.json?label=id:node_6956889

Pic 1:
![Schermata 2023-09-06 alle 19 19 10](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/a6dd5c95-c091-4979-9f0d-3857d478e409)
Pic 2:
![Schermata 2023-09-06 alle 19 19 30](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/0f547e13-ab8b-4ef3-9b63-d24d99ca5b3e)

I suspect they are the same lineage 
in the WW tree you can spot in the bottom one  the EG.5.1.3 defining  Orf1a:R542C 

Consider that EG.10 emerged in Germany with both 344T and 403K so also contamination is likely.

**Comment by AngieHinrichs** [comment]
I'm not sure I follow why those two trees might be the same lineage because they have distinct mutations.  The Pic 2 env/Germany sequences are placed one node upstream of EG.5.1.1 (missing 21718 but I'm not sure whether that's because of N or reference allele) plus G22592A,G22770A.  The Pic 1 sequences are EG.5.1.1 > C25572T > G13627A > C6541T > C12053T > C503T,A8116G.  ?

But I will try a remove & re-place on the Pic 2 set in case they have Ns and are imputed somewhere better now.

**Comment by FedeGueli** [comment]
thank you @AngieHinrichs closing it for now!
