### ISSUE TITLE
FK.1 .4 (S:S704L), with  S:G181A 24 seqs AUS,NZ,USA

### ISSUE THREAD

**Issue by Sinickle** [sars-cov-2-variants/lineage-proposals#88]
spike_d215g,spike_s704l,spike_q613h **NOW DESIGNATED FK.1.4**
spike_d215g,spike_s704l,spike_q613h,spike_g181A
[CoV-Spec
](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?aaMutations=s%3A181a%2Cs%3A215g%2Cs%3A613h&)

Right now this stands out on growth advantage globally, especially with the S:G181A mutation (but trivial seq count). S:S704L shows up often, and FK.1 is already the most fit of the BA.2.75*. S:G181A is similar to S:180V in XBB.1.16*, so maybe it does provide some advantage. However, the vast majority of the sequences are in Australia, so I'm not sure if the growth advantage over FK.1 is real. 

[USHER](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_319b9_ae85e0.json)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94097102/f4aef926-a949-4eae-8798-34df2143a290)

**Comment by FedeGueli** [comment]
Def an interesting one. I would like to see if it could start expanding outside Australia before proposing officially. thx for catching it

**Comment by krosa1910** [comment]
Very interesting mutations.
First, S:704L is most familiar to us in BA.2.12*. BA.2.12.1 was forecast to be something but turned out to be not as fast as anticipated. The other appearance of this mutation is rather sporadic, with a noticeable one recently within XBB.1.5.58*, although I don't think it is very successful.
S:181A is another story. It was proposed to be a very profitable mutation , and independently acquired by quite a lot of waves from early variants to alpha, delta and BAs despite seldom exceeding 0.3% at any time. Its most successful attempt of showing to the surface would be BF.6 to me, reaching around 2k then. It is on the rise though, and I think this one is among some interesting variants to monitor.

**Comment by FedeGueli** [comment]
65/12 today

**Comment by HynnSpylor** [comment]
89/26 today
I suggest to propose in main page

**Comment by FedeGueli** [comment]
Agree with @HynnSpylor 
@Sinickle please propose it

**Comment by FedeGueli** [comment]
The parental has been designated FK.1.4  with https://github.com/cov-lineages/pango-designation/commit/4349543b40300c8f7941e5e451d08506a9a86cdc

**Comment by FedeGueli** [comment]
@Sinickle this grew to 24 better tracking it for a bit more.

**Comment by FedeGueli** [comment]
you were right it didnt show up in the last NZL batch better closing it.
