### ISSUE TITLE
EG.5.1.3/GK.4 recomb that may be removed by usher

### ISSUE THREAD

**Issue by aviczhl2** [sars-cov-2-variants/lineage-proposals#990]
@AngieHinrichs, there is a new EG.5.1.3/GK.4 recomb that may be removed by usher, with 
GK.4-Orf1b and Spike+478R and other parts being EG.5.1.3.  Please keep it on usher.

Belgium/UGent-1525/2023|EPI_ISL_18403135|2023-10-04

[usher](https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice42_genome_218ea_f2690.json?f_userOrOld=uploaded%20sample&label=id:node_3419512&s=hCoV-19/Belgium/UGent-1524/2023%7CEPI_ISL_18403134%7C2023-10-01)
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/10445944/34e42c1e-0706-4b9b-9f25-b144236279ed)

**Comment by AngieHinrichs** [comment]
Hi @aviczhl2, as of today's build (2023-10-19) I am sparing all sequences in sars-cov-2-variants/lineage-proposals/recombinants.tsv from the usual filters -- so you no longer need to let me know the IDs, if you have added them to that file!  

I don't see EPI_ISL_18403135 in that file, but it wasn't excluded by the filters in today's build anyway.  It was not in yesterday's build because it was not yet present in the fasta that we downloaded from GISAID the night before.

**Comment by aviczhl2** [comment]
> Hi @aviczhl2, as of today's build (2023-10-19) I am sparing all sequences in sars-cov-2-variants/lineage-proposals/recombinants.tsv from the usual filters -- so you no longer need to let me know the IDs, if you have added them to that file!
> 
> I don't see EPI_ISL_18403135 in that file, but it wasn't excluded by the filters in today's build anyway. It was not in yesterday's build because it was not yet present in the fasta that we downloaded from GISAID the night before.

Sure. I'll add these seqs to that file. Previously only adding those >1 seq "real proposal" ones.

**Comment by aviczhl2** [comment]
Closing these singlet proposals and adding them to recombinants.tsv.
