### ISSUE TITLE
XBB.1.16/XBC.1.6 recombinant 18 samples Australia

### ISSUE THREAD

**Issue by JosetteSchoenma** [sars-cov-2-variants/lineage-proposals#992]
**EDITED**: _This was first spotted by @ryhisner in https://github.com/sars-cov-2-variants/lineage-proposals/issues/400 , then it seemed dying off until @JosetteSchoenma rediscovered it and analysed it further._

Query T3802C, G7091A, C25708T
9 samples
EPI_ISL_18411395
EPI_ISL_18410952
EPI_ISL_18396131
EPI_ISL_18396104
EPI_ISL_18324919
EPI_ISL_18324890
EPI_ISL_17975448
EPI_ISL_17975402
EPI_ISL_17924212

Looks like more than 1 breaking point. I will run a Sc2rf and add more info later.
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/65f6c5a1-018c-421f-a50c-fd9dbf6a66f5)

Compared to XBC.1.6 
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/ad1b55ea-4b07-4533-af37-b61b30d8c996)

Rapid overview:(edited)
![Schermata 2023-10-20 alle 14 55 04](https://github.com/sars-cov-2-variants/lineage-proposals/assets/87669813/4e14b6a4-0d1e-483c-a862-11eeeb2b6ba6)

**Comment by JosetteSchoenma** [comment]
I think is has got 4 breaking points
FU - |4321 - 6196 (ORF1a)| - XBC - |23670 (S) - 26060 (ORF3a)| - FU - |26275 (E) - 26767 (M)| - XBC - |27915 (no ORF8*) - 28297 (ORF9b)| - FU
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/19af52cd-7ef0-4ddc-a94f-ab77596d867e)

**Comment by JosetteSchoenma** [comment]
New one from Queensland. 
EPI_ISL_18435095
This makes 2 for Queensland, South Australia, and Australian Capital territory and 4 for New South Wales.

**Comment by JosetteSchoenma** [comment]
2 new ones from South Australia. Looks like GISAID hold them back for a while. Recent EPI_ISL numbers but a week old submission dates. 
EPI_ISL_18453819
EPI_ISL_18453803
![image](https://github.com/sars-cov-2-variants/lineage-proposals/assets/94831035/4c26d47b-0f54-4255-b776-f1cc7df1b95e)

**Comment by FedeGueli** [comment]
Josette i was looking a bit deeper into this it is very interesting it kept the orf8 not expressed via 27890T and Orf8:K2T (instead of the Orf8*)  and also kept the new  shorter Orf7b described by @Ryhisner gaining the double mutated XBB.1.16 Orf9b in this linegae triple mutated and instead it has Orf6 restored as XBC while keeping E:9/E:11 from BA.2.75 and instead M from Delta.

So if would like to divide its protein for ancestor we would have:
NSp1-NSP3 from BA.2.10 (BJ.1)
NSP3-NSP16 , from Delta
NTD from Delta/XBC
RBD from BA.2/XBC.1.6 
FCS S2 from BA.2
ORF3A from BA.2
E from BA.2.75
M from Delta
Orf7a from Delta
Orf7b New shape via XBC
Orf8 ablated via XBC
Orf9b from XBB.1.16 with three mutations
N = BA.2

**Comment by FedeGueli** [comment]
@ryhisner spotted this long time ago : https://github.com/sars-cov-2-variants/lineage-proposals/issues/400 then it seemed disappeared ! But it is the same. 
I think @JosetteSchoenma got right all the breakpoints so i leave this open ! i will add credit to Ryan! Sorry for not understanding it was the same but some difference in the proposal fooled me.

**Comment by FedeGueli** [comment]
+2 NSW

**Comment by JosetteSchoenma** [comment]
+2 NSW

**Comment by FedeGueli** [comment]
Pls propose once it reaches 25

**Comment by FedeGueli** [comment]
+3 QLD, NSw

**Comment by FedeGueli** [comment]
+1 VIC

@JosetteSchoenma lets wait next few uplaods from Australia to see if it is still there or not.

**Comment by FedeGueli** [comment]
re closing this
